/**
 * GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/build-standards.js
 * To update, modify the source data and run: npm run build-standards
 * 
 * Generated: 2025-07-26T13:12:51.556Z
 * Source standards: 146
 * Output standards: 146
 */

import type { ISODINStandard } from './standards';

/**
 * Generated list of fastener standards with cross-references
 */
export const generatedStandards: ISODINStandard[] = [
  {
    id: "iso225",
    description: "Symbols and descriptions of dimensions",
    designations: [
      {
        system: "ISO",
        code: "225"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 225:2010"
  },
  {
    id: "iso272",
    description: "Hexagon products - Widths across flats",
    designations: [
      {
        system: "ISO",
        code: "272"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    category: "hex",
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 272:1982/DAmd 1"
  },
  {
    id: "iso273",
    description: "Clearance holes for bolts and screws",
    designations: [
      {
        system: "ISO",
        code: "273"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 273:1979"
  },
  {
    id: "iso887",
    description: "Plain washers for metric bolts, screws and nuts for general purposes — General plan",
    designations: [
      {
        system: "ISO",
        code: "887"
      },
      {
        system: "DIN",
        code: "125"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 887:2000"
  },
  {
    id: "iso898",
    description: "Mechanical properties of fasteners",
    designations: [
      {
        system: "ISO",
        code: "898"
      },
      {
        system: "DIN",
        code: "267"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "set",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 898-5:2012"
  },
  {
    id: "iso1051",
    description: "Rivet shank diameters",
    designations: [
      {
        system: "ISO",
        code: "1051"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 1051:1999"
  },
  {
    id: "iso1207",
    description: "Slotted cheese head screws — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "1207"
      },
      {
        system: "DIN",
        code: "84"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "cheese",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 1207:2011"
  },
  {
    id: "iso1234",
    description: "Split pins",
    designations: [
      {
        system: "ISO",
        code: "1234"
      },
      {
        system: "DIN",
        code: "94"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 1234:1997"
  },
  {
    id: "iso1478",
    description: "Tapping screws thread",
    designations: [
      {
        system: "ISO",
        code: "1478"
      },
      {
        system: "DIN",
        code: "7970"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.040.30"
    ],
    reference: "ISO 1478:1999"
  },
  {
    id: "iso1479",
    description: "Hexagon head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "1479"
      },
      {
        system: "DIN",
        code: "7976"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 1479:2011"
  },
  {
    id: "iso1481",
    description: "Slotted pan head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "1481"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "pan",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 1481:2011"
  },
  {
    id: "iso1482",
    description: "Slotted countersunk (flat) head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "1482"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 1482:2011"
  },
  {
    id: "iso1483",
    description: "Slotted raised countersunk (oval) head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "1483"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 1483:2011"
  },
  {
    id: "iso1580",
    description: "Slotted pan head screws — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "1580"
      },
      {
        system: "DIN",
        code: "85"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "pan",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 1580:2011"
  },
  {
    id: "iso1891",
    description: "Fasteners — Vocabulary — Part 4: Control, inspection, delivery, acceptance and quality",
    designations: [
      {
        system: "ISO",
        code: "1891"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01",
      "01.040.21"
    ],
    reference: "ISO 1891-4:2018"
  },
  {
    id: "iso2009",
    description: "Slotted countersunk flat head screws — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "2009"
      },
      {
        system: "DIN",
        code: "963"
      },
      {
        system: "DIN",
        code: "964"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 2009:2011"
  },
  {
    id: "iso2010",
    description: "Slotted raised countersunk head screws — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "2010"
      },
      {
        system: "DIN",
        code: "965"
      },
      {
        system: "DIN",
        code: "966"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 2010:2011"
  },
  {
    id: "iso2320",
    description: "Fasteners — Prevailing torque steel nuts — Functional properties",
    designations: [
      {
        system: "ISO",
        code: "2320"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 2320:2015"
  },
  {
    id: "iso2338",
    description: "Parallel pins, of unhardened steel and austenitic stainless steel",
    designations: [
      {
        system: "ISO",
        code: "2338"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 2338:1997"
  },
  {
    id: "iso2339",
    description: "Taper pins, unhardened",
    designations: [
      {
        system: "ISO",
        code: "2339"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 2339:1986"
  },
  {
    id: "iso2340",
    description: "Clevis pins without head",
    designations: [
      {
        system: "ISO",
        code: "2340"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 2340:1986"
  },
  {
    id: "iso2341",
    description: "Clevis pins with head",
    designations: [
      {
        system: "ISO",
        code: "2341"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 2341:1986"
  },
  {
    id: "iso2342",
    description: "Slotted headless screws with shank",
    designations: [
      {
        system: "ISO",
        code: "2342"
      },
      {
        system: "DIN",
        code: "551"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 2342:2003"
  },
  {
    id: "iso2702",
    description: "Fasteners — Heat treated tapping screws — Mechanical and physical properties",
    designations: [
      {
        system: "ISO",
        code: "2702"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 2702:2022"
  },
  {
    id: "iso3506",
    description: "Stainless steel fasteners",
    designations: [
      {
        system: "ISO",
        code: "3506"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 3506-1:2009/WD Amd 1"
  },
  {
    id: "iso3508",
    description: "Thread run-outs for fasteners with thread in accordance with ISO 261 and ISO 262",
    designations: [
      {
        system: "ISO",
        code: "3508"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 3508:1976"
  },
  {
    id: "iso3800",
    description: "Threaded fasteners — Axial load fatigue testing — Test methods and evaluation of results",
    designations: [
      {
        system: "ISO",
        code: "3800"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 3800:1993"
  },
  {
    id: "iso4014",
    description: "Fasteners — Hexagon head bolts — Product grades A and B",
    designations: [
      {
        system: "ISO",
        code: "4014"
      },
      {
        system: "DIN",
        code: "931"
      },
      {
        system: "ANSI",
        code: "B18.2.3.1M"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4014:2022"
  },
  {
    id: "iso4015",
    description: "Fasteners — Hexagon head bolts with reduced shank (shank diameter ≈ pitch diameter) — Product grade B",
    designations: [
      {
        system: "ISO",
        code: "4015"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4015:2022"
  },
  {
    id: "iso4016",
    description: "Fasteners — Hexagon head bolts — Product grade C",
    designations: [
      {
        system: "ISO",
        code: "4016"
      },
      {
        system: "DIN",
        code: "601"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4016:2022"
  },
  {
    id: "iso4017",
    description: "Fasteners — Hexagon head screws — Product grades A and B",
    designations: [
      {
        system: "ISO",
        code: "4017"
      },
      {
        system: "DIN",
        code: "933"
      },
      {
        system: "ANSI",
        code: "B18.2.3.1M"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4017:2022"
  },
  {
    id: "iso4018",
    description: "Fasteners — Hexagon head screws — Product grade C",
    designations: [
      {
        system: "ISO",
        code: "4018"
      },
      {
        system: "DIN",
        code: "558"
      },
      {
        system: "DIN",
        code: "561"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4018:2022"
  },
  {
    id: "iso4032",
    description: "Fasteners — Hexagon regular nuts (style 1)",
    designations: [
      {
        system: "ISO",
        code: "4032"
      },
      {
        system: "DIN",
        code: "934"
      },
      {
        system: "ANSI",
        code: "B18.2.4.1M"
      },
      {
        system: "PN",
        code: "82144"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 4032:2023"
  },
  {
    id: "iso4033",
    description: "Fasteners — Hexagon high nuts (style 2)",
    designations: [
      {
        system: "ISO",
        code: "4033"
      },
      {
        system: "DIN",
        code: "982"
      },
      {
        system: "ANSI",
        code: "B18.2.4.2M"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 4033:2023"
  },
  {
    id: "iso4035",
    description: "Fasteners — Hexagon thin nuts (style 0)",
    designations: [
      {
        system: "ISO",
        code: "4035"
      },
      {
        system: "DIN",
        code: "439"
      },
      {
        system: "ANSI",
        code: "B18.2.4.5M"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 4035:2023"
  },
  {
    id: "iso4042",
    description: "Fasteners — Electroplated coating systems",
    designations: [
      {
        system: "ISO",
        code: "4042"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 4042:2022"
  },
  {
    id: "iso4162",
    description: "Hexagon bolts with flange — Small series — Product grade A with driving feature of product grade B",
    designations: [
      {
        system: "ISO",
        code: "4162"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4162:2012"
  },
  {
    id: "iso4753",
    description: "Fasteners — Ends of parts with external ISO metric thread",
    designations: [
      {
        system: "ISO",
        code: "4753"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 4753:2011"
  },
  {
    id: "iso4755",
    description: "Fasteners — Thread undercuts for external metric ISO threads",
    designations: [
      {
        system: "ISO",
        code: "4755"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 4755:1983"
  },
  {
    id: "iso4757",
    description: "Cross recesses for screws",
    designations: [
      {
        system: "ISO",
        code: "4757"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4757:1983"
  },
  {
    id: "iso4759",
    description: "Tolerances for fasteners — Part 1: Bolts, screws, studs and nuts — Product grades A, B and C",
    designations: [
      {
        system: "ISO",
        code: "4759"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt",
      "nut"
    ],
    icsCode: [
      "21.060.10",
      "21.060.20"
    ],
    reference: "ISO 4759-1:2000"
  },
  {
    id: "iso4762",
    description: "Hexagon socket head cap screws",
    designations: [
      {
        system: "ISO",
        code: "4762"
      },
      {
        system: "DIN",
        code: "912"
      },
      {
        system: "ANSI",
        code: "B18.3"
      },
      {
        system: "PN",
        code: "82005"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4762:2004"
  },
  {
    id: "iso4766",
    description: "Fasteners — Slotted set screws with flat point",
    designations: [
      {
        system: "ISO",
        code: "4766"
      },
      {
        system: "DIN",
        code: "1481"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "set",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 4766:2024"
  },
  {
    id: "iso7040",
    description: "Fasteners — Prevailing torque hexagon nuts — Regular nuts (with non-metallic insert)",
    designations: [
      {
        system: "ISO",
        code: "7040"
      },
      {
        system: "DIN",
        code: "985"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 7040:2025"
  },
  {
    id: "iso7041",
    description: "Fasteners — Prevailing torque hexagon nuts — High nuts (with non-metallic insert)",
    designations: [
      {
        system: "ISO",
        code: "7041"
      },
      {
        system: "DIN",
        code: "982"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 7041:2025"
  },
  {
    id: "iso7042",
    description: "Fasteners — Prevailing torque hexagon nuts — High nuts (all metal)",
    designations: [
      {
        system: "ISO",
        code: "7042"
      },
      {
        system: "DIN",
        code: "980"
      },
      {
        system: "DIN",
        code: "982"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 7042:2025"
  },
  {
    id: "iso7045",
    description: "Pan head screws with type H or type Z cross recess — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "7045"
      },
      {
        system: "DIN",
        code: "7985"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "pan",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7045:2011"
  },
  {
    id: "iso7046",
    description: "Countersunk flat head screws (common head style) with type H or type Z cross recess — Product grade A — Part 1: Steel screws of property class 4.8",
    designations: [
      {
        system: "ISO",
        code: "7046"
      },
      {
        system: "DIN",
        code: "963"
      },
      {
        system: "DIN",
        code: "965"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7046-1:2011"
  },
  {
    id: "iso7047",
    description: "Raised countersunk head screws (common head style) with type H or type Z cross recess — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "7047"
      },
      {
        system: "DIN",
        code: "964"
      },
      {
        system: "DIN",
        code: "966"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7047:2011"
  },
  {
    id: "iso7048",
    description: "Cross-recessed cheese head screws",
    designations: [
      {
        system: "ISO",
        code: "7048"
      },
      {
        system: "DIN",
        code: "7971"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "cheese",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7048:2011"
  },
  {
    id: "iso7049",
    description: "Cross-recessed pan head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "7049"
      },
      {
        system: "DIN",
        code: "7981"
      },
      {
        system: "DIN",
        code: "7983"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "pan",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7049:2011"
  },
  {
    id: "iso7050",
    description: "Cross-recessed countersunk (flat) head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "7050"
      },
      {
        system: "DIN",
        code: "7982"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7050:2011"
  },
  {
    id: "iso7051",
    description: "Cross-recessed raised countersunk (oval) head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "7051"
      },
      {
        system: "DIN",
        code: "7973"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7051:2011"
  },
  {
    id: "iso7053",
    description: "Fasteners — Hexagon washer head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "7053"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7053:2019"
  },
  {
    id: "iso7089",
    description: "Plain washers — Normal series — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "7089"
      },
      {
        system: "DIN",
        code: "125"
      },
      {
        system: "ANSI",
        code: "B18.22.1"
      },
      {
        system: "PN",
        code: "82005"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 7089:2000"
  },
  {
    id: "iso7090",
    description: "Plain washers with chamfer",
    designations: [
      {
        system: "ISO",
        code: "7090"
      },
      {
        system: "DIN",
        code: "125"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 7090:2000"
  },
  {
    id: "iso7091",
    description: "Plain washers — Normal series — Product grade C",
    designations: [
      {
        system: "ISO",
        code: "7091"
      },
      {
        system: "DIN",
        code: "126"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 7091:2000"
  },
  {
    id: "iso7092",
    description: "Plain washers — Small series — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "7092"
      },
      {
        system: "DIN",
        code: "433"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 7092:2000"
  },
  {
    id: "iso7093",
    description: "Plain washers — Large series — Part 1: Product grade A",
    designations: [
      {
        system: "ISO",
        code: "7093"
      },
      {
        system: "DIN",
        code: "9021"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 7093-1:2000"
  },
  {
    id: "iso7094",
    description: "Plain washers — Extra large series — Product grade C",
    designations: [
      {
        system: "ISO",
        code: "7094"
      },
      {
        system: "DIN",
        code: "440"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 7094:2000"
  },
  {
    id: "iso7378",
    description: "Fasteners — Bolts, screws and studs — Split pin holes and wire holes",
    designations: [
      {
        system: "ISO",
        code: "7378"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7378:1983"
  },
  {
    id: "iso7379",
    description: "Hexagon socket head shoulder screws",
    designations: [
      {
        system: "ISO",
        code: "7379"
      },
      {
        system: "DIN",
        code: "6912"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7379:1983"
  },
  {
    id: "iso7380",
    description: "Button head socket screws",
    designations: [
      {
        system: "ISO",
        code: "7380"
      },
      {
        system: "DIN",
        code: "9427"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7380-1:2022"
  },
  {
    id: "iso7434",
    description: "Fasteners — Slotted set screws with cone point",
    designations: [
      {
        system: "ISO",
        code: "7434"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "set",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7434:2024"
  },
  {
    id: "iso7435",
    description: "Fasteners — Slotted set screws with dog point",
    designations: [
      {
        system: "ISO",
        code: "7435"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "set",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7435:2024"
  },
  {
    id: "iso7436",
    description: "Fasteners — Slotted set screws with cup point",
    designations: [
      {
        system: "ISO",
        code: "7436"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "set",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7436:2024"
  },
  {
    id: "iso7719",
    description: "Fasteners — Prevailing torque hexagon nuts — Regular nuts (all metal)",
    designations: [
      {
        system: "ISO",
        code: "7719"
      },
      {
        system: "DIN",
        code: "980"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 7719:2025"
  },
  {
    id: "iso7720",
    description: "Fasteners — Prevailing torque hexagon nuts — High nuts (all metal) with slot(s)",
    designations: [
      {
        system: "ISO",
        code: "7720"
      },
      {
        system: "DIN",
        code: "982"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 7720:2025"
  },
  {
    id: "iso7721",
    description: "Countersunk head screws — Head configuration and gauging",
    designations: [
      {
        system: "ISO",
        code: "7721"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 7721:1983"
  },
  {
    id: "iso8673",
    description: "Fasteners — Hexagon regular nuts (style 1), with fine pitch thread",
    designations: [
      {
        system: "ISO",
        code: "8673"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 8673:2023"
  },
  {
    id: "iso8674",
    description: "Fasteners — Hexagon high nuts (style 2), with fine pitch thread",
    designations: [
      {
        system: "ISO",
        code: "8674"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 8674:2023"
  },
  {
    id: "iso8675",
    description: "Fasteners — Hexagon thin nuts (style 0), with fine pitch thread",
    designations: [
      {
        system: "ISO",
        code: "8675"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 8675:2023"
  },
  {
    id: "iso8676",
    description: "Fasteners — Hexagon head screws, with fine pitch thread — Product grades A and B",
    designations: [
      {
        system: "ISO",
        code: "8676"
      },
      {
        system: "DIN",
        code: "961"
      },
      {
        system: "ANSI",
        code: "B18.2.3.2M"
      },
      {
        system: "ANSI",
        code: "B18.2.3.3M"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 8676:2022"
  },
  {
    id: "iso8678",
    description: "Cup head square neck bolts with small head and short neck — Product grade B",
    designations: [
      {
        system: "ISO",
        code: "8678"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "square",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 8678:1988"
  },
  {
    id: "iso8733",
    description: "Parallel pins with internal thread, of unhardened steel and austenitic stainless steel",
    designations: [
      {
        system: "ISO",
        code: "8733"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8733:1997"
  },
  {
    id: "iso8734",
    description: "Parallel pins, of hardened steel and martensitic stainless steel (Dowel pins)",
    designations: [
      {
        system: "ISO",
        code: "8734"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8734:1997"
  },
  {
    id: "iso8735",
    description: "Parallel pins with internal thread, of hardened steel and martensitic stainless steel",
    designations: [
      {
        system: "ISO",
        code: "8735"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8735:1997"
  },
  {
    id: "iso8736",
    description: "Taper pins with internal thread, unhardened",
    designations: [
      {
        system: "ISO",
        code: "8736"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8736:1986"
  },
  {
    id: "iso8737",
    description: "Taper pins with external thread, unhardened",
    designations: [
      {
        system: "ISO",
        code: "8737"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8737:1986"
  },
  {
    id: "iso8738",
    description: "Plain washers for clevis pins — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "8738"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 8738:1986"
  },
  {
    id: "iso8740",
    description: "Fasteners — Parallel grooved pins, with chamfer point — Full-length diamond grooves",
    designations: [
      {
        system: "ISO",
        code: "8740"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8740:2025"
  },
  {
    id: "iso8741",
    description: "Fasteners — Reverse-taper grooved pins — Half-length progressive grooves",
    designations: [
      {
        system: "ISO",
        code: "8741"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8741:2025"
  },
  {
    id: "iso8744",
    description: "Fasteners — Taper grooved pins — Full-length progressive grooves",
    designations: [
      {
        system: "ISO",
        code: "8744"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8744:2025"
  },
  {
    id: "iso8745",
    description: "Fasteners — Taper grooved pins — Half-length progressive grooves",
    designations: [
      {
        system: "ISO",
        code: "8745"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8745:2025"
  },
  {
    id: "iso8746",
    description: "Fasteners — Grooved pins with round head — Full-length diamond grooves",
    designations: [
      {
        system: "ISO",
        code: "8746"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    category: "round",
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8746:2025"
  },
  {
    id: "iso8747",
    description: "Fasteners — Grooved pins with countersunk head — Full-length diamond grooves",
    designations: [
      {
        system: "ISO",
        code: "8747"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8747:2025"
  },
  {
    id: "iso8748",
    description: "Spring-type straight pins — Coiled, heavy duty",
    designations: [
      {
        system: "ISO",
        code: "8748"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8748:2007"
  },
  {
    id: "iso8749",
    description: "Pins and grooved pins — Shear test",
    designations: [
      {
        system: "ISO",
        code: "8749"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8749:1986"
  },
  {
    id: "iso8750",
    description: "Spring-type straight pins — Coiled, standard duty",
    designations: [
      {
        system: "ISO",
        code: "8750"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8750:2007"
  },
  {
    id: "iso8751",
    description: "Spring-type straight pins — Coiled, light duty",
    designations: [
      {
        system: "ISO",
        code: "8751"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8751:2007"
  },
  {
    id: "iso8752",
    description: "Spring-type straight pins — Slotted, heavy duty",
    designations: [
      {
        system: "ISO",
        code: "8752"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 8752:2009"
  },
  {
    id: "iso8765",
    description: "Fasteners — Hexagon head bolts, with fine pitch thread — Product grades A and B",
    designations: [
      {
        system: "ISO",
        code: "8765"
      },
      {
        system: "DIN",
        code: "960"
      },
      {
        system: "ANSI",
        code: "B18.2.3.5M"
      },
      {
        system: "ANSI",
        code: "B18.2.3.6M"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 8765:2022"
  },
  {
    id: "iso8991",
    description: "Designation system for fasteners",
    designations: [
      {
        system: "ISO",
        code: "8991"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 8991:1986"
  },
  {
    id: "iso10509",
    description: "Hexagon flange head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "10509"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 10509:2012"
  },
  {
    id: "iso10510",
    description: "Tapping screw and washer assemblies with plain washers",
    designations: [
      {
        system: "ISO",
        code: "10510"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "flat",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 10510:2011"
  },
  {
    id: "iso10511",
    description: "Prevailing torque type hexagon thin nuts (with non-metallic insert) — Technical Corrigendum 1",
    designations: [
      {
        system: "ISO",
        code: "10511"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 10511:2012/CD Cor 1"
  },
  {
    id: "iso10512",
    description: "Fasteners — Prevailing torque hexagon nuts — Regular nuts (with non-metallic insert), with fine pitch thread",
    designations: [
      {
        system: "ISO",
        code: "10512"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 10512:2025"
  },
  {
    id: "iso10513",
    description: "Fasteners — Prevailing torque hexagon nuts — High nuts (all metal), with fine pitch thread",
    designations: [
      {
        system: "ISO",
        code: "10513"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 10513:2025"
  },
  {
    id: "iso10644",
    description: "Screw and washer assemblies made of steel with plain washers — Washer hardness classes 200 HV and 300 HV",
    designations: [
      {
        system: "ISO",
        code: "10644"
      },
      {
        system: "DIN",
        code: "7981"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 10644:2009"
  },
  {
    id: "iso10664",
    description: "Hexalobular internal driving feature for bolts and screws",
    designations: [
      {
        system: "ISO",
        code: "10664"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 10664:2014"
  },
  {
    id: "iso10669",
    description: "Plain washers for tapping screw and washer assemblies — Normal and large series — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "10669"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 10669:1999"
  },
  {
    id: "iso10673",
    description: "Plain washers for screw and washer assemblies — Small, normal and large series — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "10673"
      }
    ],
    hardwareTypes: [
      "washer"
    ],
    category: "flat",
    icsCode: [
      "21.060.30"
    ],
    reference: "ISO 10673:2009"
  },
  {
    id: "iso10683",
    description: "Fasteners — Non-electrolytically applied zinc flake coating systems",
    designations: [
      {
        system: "ISO",
        code: "10683"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01",
      "25.220.40"
    ],
    reference: "ISO 10683:2018"
  },
  {
    id: "iso12474",
    description: "Hexagon socket head cap screws with metric fine pitch thread",
    designations: [
      {
        system: "ISO",
        code: "12474"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 12474:2010"
  },
  {
    id: "iso13337",
    description: "Spring-type straight pins — Slotted, light duty",
    designations: [
      {
        system: "ISO",
        code: "13337"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 13337:2009"
  },
  {
    id: "iso13669",
    description: "Fasteners — Grooved pins — General requirements",
    designations: [
      {
        system: "ISO",
        code: "13669"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 13669:2025"
  },
  {
    id: "iso13670",
    description: "Fasteners — Reverse-taper grooved pins — One quarter-length progressive grooves on both sides",
    designations: [
      {
        system: "ISO",
        code: "13670"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 13670"
  },
  {
    id: "iso13672",
    description: "Fasteners — Parallel grooved pins — Half-length diamond grooves",
    designations: [
      {
        system: "ISO",
        code: "13672"
      }
    ],
    hardwareTypes: [
      "pin"
    ],
    icsCode: [
      "21.060.50"
    ],
    reference: "ISO 13672:2025"
  },
  {
    id: "iso14579",
    description: "Hexalobular socket head screws",
    designations: [
      {
        system: "ISO",
        code: "14579"
      },
      {
        system: "DIN",
        code: "34822"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14579:2011"
  },
  {
    id: "iso14580",
    description: "Hexalobular socket cheese head screws",
    designations: [
      {
        system: "ISO",
        code: "14580"
      },
      {
        system: "DIN",
        code: "34823"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14580:2011"
  },
  {
    id: "iso14581",
    description: "Fasteners — Hexalobular socket countersunk flat head screws (common head style) with reduced loadability",
    designations: [
      {
        system: "ISO",
        code: "14581"
      },
      {
        system: "DIN",
        code: "7988"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14581:2022"
  },
  {
    id: "iso14582",
    description: "Fasteners — Hexalobular socket countersunk head screws, high head",
    designations: [
      {
        system: "ISO",
        code: "14582"
      },
      {
        system: "DIN",
        code: "7989"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14582:2013"
  },
  {
    id: "iso14583",
    description: "Hexalobular socket pan head screws",
    designations: [
      {
        system: "ISO",
        code: "14583"
      },
      {
        system: "DIN",
        code: "7996"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14583:2011"
  },
  {
    id: "iso14584",
    description: "Hexalobular socket raised countersunk head screws",
    designations: [
      {
        system: "ISO",
        code: "14584"
      },
      {
        system: "DIN",
        code: "7997"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14584:2011"
  },
  {
    id: "iso14585",
    description: "Hexalobular socket pan head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "14585"
      },
      {
        system: "DIN",
        code: "7995"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14585:2011"
  },
  {
    id: "iso14586",
    description: "Hexalobular socket countersunk head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "14586"
      },
      {
        system: "DIN",
        code: "7995"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14586:2011"
  },
  {
    id: "iso14587",
    description: "Hexalobular socket raised countersunk (oval) head tapping screws",
    designations: [
      {
        system: "ISO",
        code: "14587"
      },
      {
        system: "DIN",
        code: "7982"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 14587:2011"
  },
  {
    id: "iso14588",
    description: "Blind rivets — Terminology and definitions",
    designations: [
      {
        system: "ISO",
        code: "14588"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40",
      "01.040.21"
    ],
    reference: "ISO 14588:2000"
  },
  {
    id: "iso14589",
    description: "Blind rivets — Mechanical testing",
    designations: [
      {
        system: "ISO",
        code: "14589"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 14589:2000"
  },
  {
    id: "iso15065",
    description: "Countersinks for countersunk head screws with head configuration in accordance with ISO 7721",
    designations: [
      {
        system: "ISO",
        code: "15065"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15065:2005"
  },
  {
    id: "iso15071",
    description: "Hexagon bolts with flange — Small series — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "15071"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15071:2011"
  },
  {
    id: "iso15072",
    description: "Hexagon bolts with flange with metric fine pitch thread — Small series — Product grade A",
    designations: [
      {
        system: "ISO",
        code: "15072"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15072:2012"
  },
  {
    id: "iso15480",
    description: "Fasteners — Hexagon washer head drilling screws with tapping screw thread",
    designations: [
      {
        system: "ISO",
        code: "15480"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "hex",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15480:2019"
  },
  {
    id: "iso15481",
    description: "Cross recessed pan head drilling screws with tapping screw thread",
    designations: [
      {
        system: "ISO",
        code: "15481"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "pan",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15481:1999"
  },
  {
    id: "iso15482",
    description: "Cross recessed countersunk head drilling screws with tapping screw thread",
    designations: [
      {
        system: "ISO",
        code: "15482"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15482:1999"
  },
  {
    id: "iso15483",
    description: "Cross recessed raised countersunk head drilling screws with tapping screw thread",
    designations: [
      {
        system: "ISO",
        code: "15483"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 15483:1999"
  },
  {
    id: "iso15973",
    description: "Closed end blind rivets with break pull mandrel and protruding head — AlA/St",
    designations: [
      {
        system: "ISO",
        code: "15973"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15973:2000"
  },
  {
    id: "iso15974",
    description: "Closed end blind rivets with break pull mandrel and countersunk head — AlA/St",
    designations: [
      {
        system: "ISO",
        code: "15974"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15974:2000"
  },
  {
    id: "iso15975",
    description: "Closed end blind rivets with break pull mandrel and protruding head — AI/AIA",
    designations: [
      {
        system: "ISO",
        code: "15975"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15975:2002"
  },
  {
    id: "iso15976",
    description: "Closed end blind rivets with break pull mandrel and protruding head — St/St",
    designations: [
      {
        system: "ISO",
        code: "15976"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15976:2002"
  },
  {
    id: "iso15977",
    description: "Open end blind rivets with break pull mandrel and protruding head — AIA/St",
    designations: [
      {
        system: "ISO",
        code: "15977"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15977:2002"
  },
  {
    id: "iso15978",
    description: "Open end blind rivets with break pull mandrel and countersunk head — AIA/St",
    designations: [
      {
        system: "ISO",
        code: "15978"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15978:2002"
  },
  {
    id: "iso15979",
    description: "Open end blind rivets with break pull mandrel and protruding head — St/St",
    designations: [
      {
        system: "ISO",
        code: "15979"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15979:2002"
  },
  {
    id: "iso15980",
    description: "Open end blind rivets with break pull mandrel and countersunk head — St/St",
    designations: [
      {
        system: "ISO",
        code: "15980"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15980:2002"
  },
  {
    id: "iso15981",
    description: "Open end blind rivets with break pull mandrel and protruding head — AIA/AIA",
    designations: [
      {
        system: "ISO",
        code: "15981"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15981:2002"
  },
  {
    id: "iso15982",
    description: "Open end blind rivets with break pull mandrel and countersunk head — AIA/AIA",
    designations: [
      {
        system: "ISO",
        code: "15982"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15982:2002"
  },
  {
    id: "iso15983",
    description: "Open end blind rivets with break pull mandrel and protruding head — A2/A2",
    designations: [
      {
        system: "ISO",
        code: "15983"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15983:2002"
  },
  {
    id: "iso15984",
    description: "Open end blind rivets with break pull mandrel and countersunk head — A2/A2",
    designations: [
      {
        system: "ISO",
        code: "15984"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 15984:2002"
  },
  {
    id: "iso16228",
    description: "Fasteners — Types of inspection documents",
    designations: [
      {
        system: "ISO",
        code: "16228"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 16228:2017"
  },
  {
    id: "iso16426",
    description: "Fasteners — Quality assurance system",
    designations: [
      {
        system: "ISO",
        code: "16426"
      }
    ],
    hardwareTypes: [
      "fastener"
    ],
    icsCode: [
      "21.060.01"
    ],
    reference: "ISO 16426:2002"
  },
  {
    id: "iso16582",
    description: "Open end blind rivets with break pull mandrel and protruding head — Cu/St or Cu/Br or Cu/SSt",
    designations: [
      {
        system: "ISO",
        code: "16582"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 16582:2002"
  },
  {
    id: "iso16583",
    description: "Open end blind rivets with break pull mandrel and countersunk head — Cu/St or Cu/Br or Cu/SSt",
    designations: [
      {
        system: "ISO",
        code: "16583"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    category: "countersunk",
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 16583:2002"
  },
  {
    id: "iso16584",
    description: "Open end blind rivets with break pull mandrel and protruding head — NiCu/St or NiCu/SSt",
    designations: [
      {
        system: "ISO",
        code: "16584"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 16584:2002"
  },
  {
    id: "iso16585",
    description: "Closed end blind rivets with pull mandrel and protruding head — A2/SSt",
    designations: [
      {
        system: "ISO",
        code: "16585"
      }
    ],
    hardwareTypes: [
      "rivet"
    ],
    icsCode: [
      "21.060.40"
    ],
    reference: "ISO 16585:2002"
  },
  {
    id: "iso21670",
    description: "Fasteners — Hexagon weld nuts with flange",
    designations: [
      {
        system: "ISO",
        code: "21670"
      }
    ],
    hardwareTypes: [
      "nut"
    ],
    category: "hex",
    icsCode: [
      "21.060.20"
    ],
    reference: "ISO 21670:2014"
  },
  {
    id: "iso23429",
    description: "Gauging of hexagon sockets",
    designations: [
      {
        system: "ISO",
        code: "23429"
      }
    ],
    hardwareTypes: [
      "screw",
      "bolt"
    ],
    category: "socket",
    icsCode: [
      "21.060.10"
    ],
    reference: "ISO 23429:2004"
  }
] as const;

/**
 * Get all unique hardware types from generated standards
 */
export const hardwareTypes = Array.from(
  new Set(generatedStandards.flatMap(s => s.hardwareTypes))
).sort();

/**
 * Get all unique categories from generated standards
 */
export const categories = Array.from(
  new Set(generatedStandards.map(s => s.category).filter(Boolean))
).sort();
