/**
 * GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated by scripts/build-all-standards.js
 * To update, modify the source data and run: npm run build-standards
 *
 * Generated: 2025-07-27T10:11:45.367Z
 * Total standards: 247
 * ISO standards: 145
 * DIN-only standards: 102
 * Standards with images: 128
 */

import type { ISODINStandard } from './standards';

/**
 * Generated list of fastener standards with cross-references
 */
export const generatedStandards: ISODINStandard[] = [
	{
		id: 'iso225',
		primarySystem: 'ISO',
		description:
			'Fasteners — Bolts, screws, studs and nuts — Symbols and descriptions of dimensions',
		designations: [
			{
				system: 'ISO',
				code: '225'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 225:2010'
	},
	{
		id: 'iso272',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon products — Widths across flats — Amendment 1',
		designations: [
			{
				system: 'ISO',
				code: '272'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 272:1982/DAmd 1'
	},
	{
		id: 'iso273',
		primarySystem: 'ISO',
		description: 'Fasteners — Clearance holes for bolts and screws',
		designations: [
			{
				system: 'ISO',
				code: '273'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 273:1979'
	},
	{
		id: 'iso887',
		primarySystem: 'ISO',
		description:
			'Plain washers for metric bolts, screws and nuts for general purposes — General plan',
		designations: [
			{
				system: 'ISO',
				code: '887'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 887:2000'
	},
	{
		id: 'iso898',
		primarySystem: 'ISO',
		description:
			'Mechanical properties of fasteners made of carbon steel and alloy steel — Part 5: Set screws and similar threaded fasteners with specified hardness classes — Coarse thread and fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '898'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 898-5:2012'
	},
	{
		id: 'iso1051',
		primarySystem: 'ISO',
		description: 'Rivet shank diameters',
		designations: [
			{
				system: 'ISO',
				code: '1051'
			},
			{
				system: 'DIN',
				code: '660'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 1051:1999'
	},
	{
		id: 'iso1207',
		primarySystem: 'ISO',
		description: 'Slotted cheese head screws — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '1207'
			},
			{
				system: 'DIN',
				code: '84'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 1207:2011'
	},
	{
		id: 'iso1234',
		primarySystem: 'ISO',
		description: 'Split pins',
		designations: [
			{
				system: 'ISO',
				code: '1234'
			},
			{
				system: 'DIN',
				code: '94'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 1234:1997'
	},
	{
		id: 'iso1479',
		primarySystem: 'ISO',
		description: 'Hexagon head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '1479'
			},
			{
				system: 'DIN',
				code: '7976'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 1479:2011'
	},
	{
		id: 'iso1481',
		primarySystem: 'ISO',
		description: 'Slotted pan head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '1481'
			},
			{
				system: 'DIN',
				code: '7971'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 1481:2011'
	},
	{
		id: 'iso1482',
		primarySystem: 'ISO',
		description: 'Slotted countersunk (flat) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '1482'
			},
			{
				system: 'DIN',
				code: '7972'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 1482:2011'
	},
	{
		id: 'iso1483',
		primarySystem: 'ISO',
		description: 'Slotted raised countersunk (oval) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '1483'
			},
			{
				system: 'DIN',
				code: '7973'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 1483:2011'
	},
	{
		id: 'iso1580',
		primarySystem: 'ISO',
		description: 'Slotted pan head screws — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '1580'
			},
			{
				system: 'DIN',
				code: '85'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 1580:2011'
	},
	{
		id: 'iso1891',
		primarySystem: 'ISO',
		description:
			'Fasteners — Vocabulary — Part 4: Control, inspection, delivery, acceptance and quality',
		designations: [
			{
				system: 'ISO',
				code: '1891'
			}
		],
		icsCode: ['21.060.01', '01.040.21'],
		reference: 'ISO 1891-4:2018'
	},
	{
		id: 'iso2009',
		primarySystem: 'ISO',
		description: 'Slotted countersunk flat head screws — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '2009'
			},
			{
				system: 'DIN',
				code: '963'
			},
			{
				system: 'DIN',
				code: '964'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 2009:2011'
	},
	{
		id: 'iso2010',
		primarySystem: 'ISO',
		description: 'Slotted raised countersunk head screws — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '2010'
			},
			{
				system: 'DIN',
				code: '965'
			},
			{
				system: 'DIN',
				code: '966'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 2010:2011'
	},
	{
		id: 'iso2320',
		primarySystem: 'ISO',
		description: 'Fasteners — Prevailing torque steel nuts — Functional properties',
		designations: [
			{
				system: 'ISO',
				code: '2320'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 2320:2015'
	},
	{
		id: 'iso2338',
		primarySystem: 'ISO',
		description: 'Parallel pins, of unhardened steel and austenitic stainless steel',
		designations: [
			{
				system: 'ISO',
				code: '2338'
			},
			{
				system: 'DIN',
				code: '7'
			},
			{
				system: 'DIN',
				code: '6325'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 2338:1997'
	},
	{
		id: 'iso2339',
		primarySystem: 'ISO',
		description: 'Taper pins, unhardened',
		designations: [
			{
				system: 'ISO',
				code: '2339'
			},
			{
				system: 'DIN',
				code: '1'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 2339:1986'
	},
	{
		id: 'iso2340',
		primarySystem: 'ISO',
		description: 'Clevis pins without head',
		designations: [
			{
				system: 'ISO',
				code: '2340'
			},
			{
				system: 'DIN',
				code: '1433'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 2340:1986'
	},
	{
		id: 'iso2341',
		primarySystem: 'ISO',
		description: 'Clevis pins with head',
		designations: [
			{
				system: 'ISO',
				code: '2341'
			},
			{
				system: 'DIN',
				code: '1443'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 2341:1986'
	},
	{
		id: 'iso2342',
		primarySystem: 'ISO',
		description: 'Slotted headless screws with shank',
		designations: [
			{
				system: 'ISO',
				code: '2342'
			},
			{
				system: 'DIN',
				code: '551'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 2342:2003'
	},
	{
		id: 'iso2702',
		primarySystem: 'ISO',
		description: 'Fasteners — Heat treated tapping screws — Mechanical and physical properties',
		designations: [
			{
				system: 'ISO',
				code: '2702'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 2702:2022'
	},
	{
		id: 'iso3506',
		primarySystem: 'ISO',
		description:
			'Mechanical properties of corrosion-resistant stainless steel fasteners — Part 1: Bolts, screws and studs — Amendment 1',
		designations: [
			{
				system: 'ISO',
				code: '3506'
			},
			{
				system: 'DIN',
				code: '267'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 3506-1:2009/WD Amd 1'
	},
	{
		id: 'iso3508',
		primarySystem: 'ISO',
		description: 'Thread run-outs for fasteners with thread in accordance with ISO 261 and ISO 262',
		designations: [
			{
				system: 'ISO',
				code: '3508'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 3508:1976'
	},
	{
		id: 'iso3800',
		primarySystem: 'ISO',
		description:
			'Threaded fasteners — Axial load fatigue testing — Test methods and evaluation of results',
		designations: [
			{
				system: 'ISO',
				code: '3800'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 3800:1993'
	},
	{
		id: 'iso4014',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon head bolts — Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '4014'
			},
			{
				system: 'DIN',
				code: '931'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4014:2022',
		image: '/images/standards/din_931.jpg'
	},
	{
		id: 'iso4015',
		primarySystem: 'ISO',
		description:
			'Fasteners — Hexagon head bolts with reduced shank (shank diameter ≈ pitch diameter) — Product grade B',
		designations: [
			{
				system: 'ISO',
				code: '4015'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4015:2022'
	},
	{
		id: 'iso4016',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon head bolts — Product grade C',
		designations: [
			{
				system: 'ISO',
				code: '4016'
			},
			{
				system: 'DIN',
				code: '601'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4016:2022'
	},
	{
		id: 'iso4017',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon head screws — Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '4017'
			},
			{
				system: 'DIN',
				code: '933'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4017:2022',
		image: '/images/standards/din_933.jpg'
	},
	{
		id: 'iso4018',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon head screws — Product grade C',
		designations: [
			{
				system: 'ISO',
				code: '4018'
			},
			{
				system: 'DIN',
				code: '558'
			},
			{
				system: 'DIN',
				code: '561'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4018:2022',
		image: '/images/standards/din_561.jpg'
	},
	{
		id: 'iso4032',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon regular nuts (style 1)',
		designations: [
			{
				system: 'ISO',
				code: '4032'
			},
			{
				system: 'DIN',
				code: '934'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 4032:2023',
		image: '/images/standards/din_934.jpg'
	},
	{
		id: 'iso4033',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon high nuts (style 2)',
		designations: [
			{
				system: 'ISO',
				code: '4033'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 4033:2023',
		image: '/images/standards/din_982.jpg'
	},
	{
		id: 'iso4035',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon thin nuts (style 0)',
		designations: [
			{
				system: 'ISO',
				code: '4035'
			},
			{
				system: 'DIN',
				code: '439'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 4035:2023',
		image: '/images/standards/din_439.jpg'
	},
	{
		id: 'iso4042',
		primarySystem: 'ISO',
		description: 'Fasteners — Electroplated coating systems',
		designations: [
			{
				system: 'ISO',
				code: '4042'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 4042:2022'
	},
	{
		id: 'iso4162',
		primarySystem: 'ISO',
		description:
			'Hexagon bolts with flange — Small series — Product grade A with driving feature of product grade B',
		designations: [
			{
				system: 'ISO',
				code: '4162'
			},
			{
				system: 'DIN',
				code: '6921'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4162:2012',
		image: '/images/standards/din_6921.jpg'
	},
	{
		id: 'iso4753',
		primarySystem: 'ISO',
		description: 'Fasteners — Ends of parts with external ISO metric thread',
		designations: [
			{
				system: 'ISO',
				code: '4753'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 4753:2011'
	},
	{
		id: 'iso4755',
		primarySystem: 'ISO',
		description: 'Fasteners — Thread undercuts for external metric ISO threads',
		designations: [
			{
				system: 'ISO',
				code: '4755'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 4755:1983'
	},
	{
		id: 'iso4757',
		primarySystem: 'ISO',
		description: 'Cross recesses for screws',
		designations: [
			{
				system: 'ISO',
				code: '4757'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4757:1983'
	},
	{
		id: 'iso4759',
		primarySystem: 'ISO',
		description:
			'Tolerances for fasteners — Part 1: Bolts, screws, studs and nuts — Product grades A, B and C',
		designations: [
			{
				system: 'ISO',
				code: '4759'
			}
		],
		icsCode: ['21.060.10', '21.060.20'],
		reference: 'ISO 4759-1:2000'
	},
	{
		id: 'iso4762',
		primarySystem: 'ISO',
		description: 'Hexagon socket head cap screws',
		designations: [
			{
				system: 'ISO',
				code: '4762'
			},
			{
				system: 'DIN',
				code: '912'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4762:2004',
		image: '/images/standards/din_912.jpg'
	},
	{
		id: 'iso4766',
		primarySystem: 'ISO',
		description: 'Fasteners — Slotted set screws with flat point',
		designations: [
			{
				system: 'ISO',
				code: '4766'
			},
			{
				system: 'DIN',
				code: '1481'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 4766:2024'
	},
	{
		id: 'iso7040',
		primarySystem: 'ISO',
		description:
			'Fasteners — Prevailing torque hexagon nuts — Regular nuts (with non-metallic insert)',
		designations: [
			{
				system: 'ISO',
				code: '7040'
			},
			{
				system: 'DIN',
				code: '985'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 7040:2025',
		image: '/images/standards/iso_7040.jpg'
	},
	{
		id: 'iso7041',
		primarySystem: 'ISO',
		description:
			'Fasteners — Prevailing torque hexagon nuts — High nuts (with non-metallic insert)',
		designations: [
			{
				system: 'ISO',
				code: '7041'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 7041:2025'
	},
	{
		id: 'iso7042',
		primarySystem: 'ISO',
		description: 'Fasteners — Prevailing torque hexagon nuts — High nuts (all metal)',
		designations: [
			{
				system: 'ISO',
				code: '7042'
			},
			{
				system: 'DIN',
				code: '980'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 7042:2025',
		image: '/images/standards/din_980.jpg'
	},
	{
		id: 'iso7045',
		primarySystem: 'ISO',
		description: 'Pan head screws with type H or type Z cross recess — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7045'
			},
			{
				system: 'DIN',
				code: '7985'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7045:2011'
	},
	{
		id: 'iso7046',
		primarySystem: 'ISO',
		description:
			'Countersunk flat head screws (common head style) with type H or type Z cross recess — Product grade A — Part 1: Steel screws of property class 4.8',
		designations: [
			{
				system: 'ISO',
				code: '7046'
			},
			{
				system: 'DIN',
				code: '963'
			},
			{
				system: 'DIN',
				code: '965'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7046-1:2011'
	},
	{
		id: 'iso7047',
		primarySystem: 'ISO',
		description:
			'Raised countersunk head screws (common head style) with type H or type Z cross recess — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7047'
			},
			{
				system: 'DIN',
				code: '964'
			},
			{
				system: 'DIN',
				code: '966'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7047:2011'
	},
	{
		id: 'iso7048',
		primarySystem: 'ISO',
		description: 'Cross-recessed cheese head screws',
		designations: [
			{
				system: 'ISO',
				code: '7048'
			},
			{
				system: 'DIN',
				code: '7971'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7048:2011'
	},
	{
		id: 'iso7049',
		primarySystem: 'ISO',
		description: 'Cross-recessed pan head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7049'
			},
			{
				system: 'DIN',
				code: '7981'
			},
			{
				system: 'DIN',
				code: '7983'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7049:2011'
	},
	{
		id: 'iso7050',
		primarySystem: 'ISO',
		description: 'Cross-recessed countersunk (flat) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7050'
			},
			{
				system: 'DIN',
				code: '7982'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7050:2011'
	},
	{
		id: 'iso7051',
		primarySystem: 'ISO',
		description: 'Cross-recessed raised countersunk (oval) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7051'
			},
			{
				system: 'DIN',
				code: '7973'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7051:2011'
	},
	{
		id: 'iso7053',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon washer head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7053'
			},
			{
				system: 'DIN',
				code: '7967'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7053:2019',
		image: '/images/standards/din_7967.jpg'
	},
	{
		id: 'iso7089',
		primarySystem: 'ISO',
		description: 'Plain washers — Normal series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7089'
			},
			{
				system: 'DIN',
				code: '125'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 7089:2000',
		image: '/images/standards/din_125.jpg'
	},
	{
		id: 'iso7090',
		primarySystem: 'ISO',
		description: 'Plain washers, chamfered — Normal series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7090'
			},
			{
				system: 'DIN',
				code: '125'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 7090:2000'
	},
	{
		id: 'iso7091',
		primarySystem: 'ISO',
		description: 'Plain washers — Normal series — Product grade C',
		designations: [
			{
				system: 'ISO',
				code: '7091'
			},
			{
				system: 'DIN',
				code: '126'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 7091:2000'
	},
	{
		id: 'iso7092',
		primarySystem: 'ISO',
		description: 'Plain washers — Small series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7092'
			},
			{
				system: 'DIN',
				code: '433'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 7092:2000',
		image: '/images/standards/din_433.jpg'
	},
	{
		id: 'iso7093',
		primarySystem: 'ISO',
		description: 'Plain washers — Large series — Part 1: Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7093'
			},
			{
				system: 'DIN',
				code: '9021'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 7093-1:2000',
		image: '/images/standards/din_9021.jpg'
	},
	{
		id: 'iso7094',
		primarySystem: 'ISO',
		description: 'Plain washers — Extra large series — Product grade C',
		designations: [
			{
				system: 'ISO',
				code: '7094'
			},
			{
				system: 'DIN',
				code: '440'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 7094:2000',
		image: '/images/standards/din_440.jpg'
	},
	{
		id: 'iso7378',
		primarySystem: 'ISO',
		description: 'Fasteners — Bolts, screws and studs — Split pin holes and wire holes',
		designations: [
			{
				system: 'ISO',
				code: '7378'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7378:1983'
	},
	{
		id: 'iso7379',
		primarySystem: 'ISO',
		description: 'Hexagon socket head shoulder screws',
		designations: [
			{
				system: 'ISO',
				code: '7379'
			},
			{
				system: 'DIN',
				code: '6912'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7379:1983',
		image: '/images/standards/iso_7379.jpg'
	},
	{
		id: 'iso7380',
		primarySystem: 'ISO',
		description:
			'Fasteners — Button head screws with reduced loadability — Part 1: Hexagon socket button head screws',
		designations: [
			{
				system: 'ISO',
				code: '7380'
			},
			{
				system: 'DIN',
				code: '9427'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7380-1:2022'
	},
	{
		id: 'iso7434',
		primarySystem: 'ISO',
		description: 'Fasteners — Slotted set screws with cone point',
		designations: [
			{
				system: 'ISO',
				code: '7434'
			},
			{
				system: 'DIN',
				code: '553'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7434:2024'
	},
	{
		id: 'iso7435',
		primarySystem: 'ISO',
		description: 'Fasteners — Slotted set screws with dog point',
		designations: [
			{
				system: 'ISO',
				code: '7435'
			},
			{
				system: 'DIN',
				code: '417'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7435:2024'
	},
	{
		id: 'iso7436',
		primarySystem: 'ISO',
		description: 'Fasteners — Slotted set screws with cup point',
		designations: [
			{
				system: 'ISO',
				code: '7436'
			},
			{
				system: 'DIN',
				code: '438'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7436:2024'
	},
	{
		id: 'iso7719',
		primarySystem: 'ISO',
		description: 'Fasteners — Prevailing torque hexagon nuts — Regular nuts (all metal)',
		designations: [
			{
				system: 'ISO',
				code: '7719'
			},
			{
				system: 'DIN',
				code: '980'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 7719:2025'
	},
	{
		id: 'iso7720',
		primarySystem: 'ISO',
		description: 'Fasteners — Prevailing torque hexagon nuts — High nuts (all metal) with slot(s)',
		designations: [
			{
				system: 'ISO',
				code: '7720'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 7720:2025'
	},
	{
		id: 'iso7721',
		primarySystem: 'ISO',
		description: 'Countersunk head screws — Head configuration and gauging',
		designations: [
			{
				system: 'ISO',
				code: '7721'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 7721:1983'
	},
	{
		id: 'iso8673',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon regular nuts (style 1), with fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '8673'
			},
			{
				system: 'DIN',
				code: '934'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 8673:2023'
	},
	{
		id: 'iso8674',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon high nuts (style 2), with fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '8674'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 8674:2023'
	},
	{
		id: 'iso8675',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon thin nuts (style 0), with fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '8675'
			},
			{
				system: 'DIN',
				code: '439'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 8675:2023'
	},
	{
		id: 'iso8676',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon head screws, with fine pitch thread — Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '8676'
			},
			{
				system: 'DIN',
				code: '961'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 8676:2022',
		image: '/images/standards/din_961.jpg'
	},
	{
		id: 'iso8678',
		primarySystem: 'ISO',
		description: 'Cup head square neck bolts with small head and short neck — Product grade B',
		designations: [
			{
				system: 'ISO',
				code: '8678'
			},
			{
				system: 'DIN',
				code: '603'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 8678:1988',
		image: '/images/standards/din_603.jpg'
	},
	{
		id: 'iso8733',
		primarySystem: 'ISO',
		description:
			'Parallel pins with internal thread, of unhardened steel and austenitic stainless steel',
		designations: [
			{
				system: 'ISO',
				code: '8733'
			},
			{
				system: 'DIN',
				code: '7979'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8733:1997'
	},
	{
		id: 'iso8734',
		primarySystem: 'ISO',
		description: 'Parallel pins, of hardened steel and martensitic stainless steel (Dowel pins)',
		designations: [
			{
				system: 'ISO',
				code: '8734'
			},
			{
				system: 'DIN',
				code: '6325'
			},
			{
				system: 'DIN',
				code: '7'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8734:1997'
	},
	{
		id: 'iso8735',
		primarySystem: 'ISO',
		description:
			'Parallel pins with internal thread, of hardened steel and martensitic stainless steel',
		designations: [
			{
				system: 'ISO',
				code: '8735'
			},
			{
				system: 'DIN',
				code: '7978'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8735:1997'
	},
	{
		id: 'iso8736',
		primarySystem: 'ISO',
		description: 'Taper pins with internal thread, unhardened',
		designations: [
			{
				system: 'ISO',
				code: '8736'
			},
			{
				system: 'DIN',
				code: '7977'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8736:1986'
	},
	{
		id: 'iso8737',
		primarySystem: 'ISO',
		description: 'Taper pins with external thread, unhardened',
		designations: [
			{
				system: 'ISO',
				code: '8737'
			},
			{
				system: 'DIN',
				code: '7977'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8737:1986'
	},
	{
		id: 'iso8738',
		primarySystem: 'ISO',
		description: 'Plain washers for clevis pins — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '8738'
			},
			{
				system: 'DIN',
				code: '1440'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 8738:1986',
		image: '/images/standards/din_1440.jpg'
	},
	{
		id: 'iso8740',
		primarySystem: 'ISO',
		description:
			'Fasteners — Parallel grooved pins, with chamfer point — Full-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '8740'
			},
			{
				system: 'DIN',
				code: '1473'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8740:2025'
	},
	{
		id: 'iso8741',
		primarySystem: 'ISO',
		description: 'Fasteners — Reverse-taper grooved pins — Half-length progressive grooves',
		designations: [
			{
				system: 'ISO',
				code: '8741'
			},
			{
				system: 'DIN',
				code: '1474'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8741:2025'
	},
	{
		id: 'iso8744',
		primarySystem: 'ISO',
		description: 'Fasteners — Taper grooved pins — Full-length progressive grooves',
		designations: [
			{
				system: 'ISO',
				code: '8744'
			},
			{
				system: 'DIN',
				code: '1471'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8744:2025'
	},
	{
		id: 'iso8745',
		primarySystem: 'ISO',
		description: 'Fasteners — Taper grooved pins — Half-length progressive grooves',
		designations: [
			{
				system: 'ISO',
				code: '8745'
			},
			{
				system: 'DIN',
				code: '1472'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8745:2025'
	},
	{
		id: 'iso8746',
		primarySystem: 'ISO',
		description: 'Fasteners — Grooved pins with round head — Full-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '8746'
			},
			{
				system: 'DIN',
				code: '1476'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8746:2025'
	},
	{
		id: 'iso8747',
		primarySystem: 'ISO',
		description: 'Fasteners — Grooved pins with countersunk head — Full-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '8747'
			},
			{
				system: 'DIN',
				code: '1477'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8747:2025'
	},
	{
		id: 'iso8748',
		primarySystem: 'ISO',
		description: 'Spring-type straight pins — Coiled, heavy duty',
		designations: [
			{
				system: 'ISO',
				code: '8748'
			},
			{
				system: 'DIN',
				code: '7343'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8748:2007'
	},
	{
		id: 'iso8749',
		primarySystem: 'ISO',
		description: 'Pins and grooved pins — Shear test',
		designations: [
			{
				system: 'ISO',
				code: '8749'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8749:1986'
	},
	{
		id: 'iso8750',
		primarySystem: 'ISO',
		description: 'Spring-type straight pins — Coiled, standard duty',
		designations: [
			{
				system: 'ISO',
				code: '8750'
			},
			{
				system: 'DIN',
				code: '7343'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8750:2007'
	},
	{
		id: 'iso8751',
		primarySystem: 'ISO',
		description: 'Spring-type straight pins — Coiled, light duty',
		designations: [
			{
				system: 'ISO',
				code: '8751'
			},
			{
				system: 'DIN',
				code: '7343'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8751:2007'
	},
	{
		id: 'iso8752',
		primarySystem: 'ISO',
		description: 'Spring-type straight pins — Slotted, heavy duty',
		designations: [
			{
				system: 'ISO',
				code: '8752'
			},
			{
				system: 'DIN',
				code: '1481'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 8752:2009'
	},
	{
		id: 'iso8765',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon head bolts, with fine pitch thread — Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '8765'
			},
			{
				system: 'DIN',
				code: '960'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 8765:2022',
		image: '/images/standards/din_960.jpg'
	},
	{
		id: 'iso8991',
		primarySystem: 'ISO',
		description: 'Designation system for fasteners',
		designations: [
			{
				system: 'ISO',
				code: '8991'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 8991:1986'
	},
	{
		id: 'iso10509',
		primarySystem: 'ISO',
		description: 'Hexagon flange head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '10509'
			},
			{
				system: 'DIN',
				code: '6923'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 10509:2012',
		image: '/images/standards/din_6923.jpg'
	},
	{
		id: 'iso10510',
		primarySystem: 'ISO',
		description: 'Tapping screw and washer assemblies with plain washers',
		designations: [
			{
				system: 'ISO',
				code: '10510'
			},
			{
				system: 'DIN',
				code: '6902'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 10510:2011'
	},
	{
		id: 'iso10511',
		primarySystem: 'ISO',
		description:
			'Prevailing torque type hexagon thin nuts (with non-metallic insert) — Technical Corrigendum 1',
		designations: [
			{
				system: 'ISO',
				code: '10511'
			},
			{
				system: 'DIN',
				code: '985'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 10511:2012/CD Cor 1'
	},
	{
		id: 'iso10512',
		primarySystem: 'ISO',
		description:
			'Fasteners — Prevailing torque hexagon nuts — Regular nuts (with non-metallic insert), with fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '10512'
			},
			{
				system: 'DIN',
				code: '985'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 10512:2025'
	},
	{
		id: 'iso10513',
		primarySystem: 'ISO',
		description:
			'Fasteners — Prevailing torque hexagon nuts — High nuts (all metal), with fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '10513'
			},
			{
				system: 'DIN',
				code: '980'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 10513:2025'
	},
	{
		id: 'iso10644',
		primarySystem: 'ISO',
		description:
			'Screw and washer assemblies made of steel with plain washers — Washer hardness classes 200 HV and 300 HV',
		designations: [
			{
				system: 'ISO',
				code: '10644'
			},
			{
				system: 'DIN',
				code: '7981'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 10644:2009'
	},
	{
		id: 'iso10664',
		primarySystem: 'ISO',
		description: 'Hexalobular internal driving feature for bolts and screws',
		designations: [
			{
				system: 'ISO',
				code: '10664'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 10664:2014'
	},
	{
		id: 'iso10669',
		primarySystem: 'ISO',
		description:
			'Plain washers for tapping screw and washer assemblies — Normal and large series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '10669'
			},
			{
				system: 'DIN',
				code: '6902'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 10669:1999'
	},
	{
		id: 'iso10673',
		primarySystem: 'ISO',
		description:
			'Plain washers for screw and washer assemblies — Small, normal and large series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '10673'
			},
			{
				system: 'DIN',
				code: '6902'
			}
		],
		icsCode: ['21.060.30'],
		reference: 'ISO 10673:2009'
	},
	{
		id: 'iso10683',
		primarySystem: 'ISO',
		description: 'Fasteners — Non-electrolytically applied zinc flake coating systems',
		designations: [
			{
				system: 'ISO',
				code: '10683'
			}
		],
		icsCode: ['21.060.01', '25.220.40'],
		reference: 'ISO 10683:2018'
	},
	{
		id: 'iso12474',
		primarySystem: 'ISO',
		description: 'Hexagon socket head cap screws with metric fine pitch thread',
		designations: [
			{
				system: 'ISO',
				code: '12474'
			},
			{
				system: 'DIN',
				code: '912'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 12474:2010'
	},
	{
		id: 'iso13337',
		primarySystem: 'ISO',
		description: 'Spring-type straight pins — Slotted, light duty',
		designations: [
			{
				system: 'ISO',
				code: '13337'
			},
			{
				system: 'DIN',
				code: '7346'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 13337:2009'
	},
	{
		id: 'iso13669',
		primarySystem: 'ISO',
		description: 'Fasteners — Grooved pins — General requirements',
		designations: [
			{
				system: 'ISO',
				code: '13669'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 13669:2025'
	},
	{
		id: 'iso13670',
		primarySystem: 'ISO',
		description:
			'Fasteners — Reverse-taper grooved pins — One quarter-length progressive grooves on both sides',
		designations: [
			{
				system: 'ISO',
				code: '13670'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 13670'
	},
	{
		id: 'iso13672',
		primarySystem: 'ISO',
		description: 'Fasteners — Parallel grooved pins — Half-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '13672'
			}
		],
		icsCode: ['21.060.50'],
		reference: 'ISO 13672:2025'
	},
	{
		id: 'iso14579',
		primarySystem: 'ISO',
		description: 'Hexalobular socket head cap screws',
		designations: [
			{
				system: 'ISO',
				code: '14579'
			},
			{
				system: 'DIN',
				code: '34822'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14579:2011'
	},
	{
		id: 'iso14580',
		primarySystem: 'ISO',
		description: 'Hexalobular socket cheese head screws',
		designations: [
			{
				system: 'ISO',
				code: '14580'
			},
			{
				system: 'DIN',
				code: '34823'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14580:2011'
	},
	{
		id: 'iso14581',
		primarySystem: 'ISO',
		description:
			'Fasteners — Hexalobular socket countersunk flat head screws (common head style) with reduced loadability',
		designations: [
			{
				system: 'ISO',
				code: '14581'
			},
			{
				system: 'DIN',
				code: '7988'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14581:2022'
	},
	{
		id: 'iso14582',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexalobular socket countersunk head screws, high head',
		designations: [
			{
				system: 'ISO',
				code: '14582'
			},
			{
				system: 'DIN',
				code: '7989'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14582:2013',
		image: '/images/standards/din_7989.jpg'
	},
	{
		id: 'iso14583',
		primarySystem: 'ISO',
		description: 'Hexalobular socket pan head screws',
		designations: [
			{
				system: 'ISO',
				code: '14583'
			},
			{
				system: 'DIN',
				code: '7996'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14583:2011',
		image: '/images/standards/din_7996.jpg'
	},
	{
		id: 'iso14584',
		primarySystem: 'ISO',
		description: 'Hexalobular socket raised countersunk head screws',
		designations: [
			{
				system: 'ISO',
				code: '14584'
			},
			{
				system: 'DIN',
				code: '7997'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14584:2011',
		image: '/images/standards/din_7997.jpg'
	},
	{
		id: 'iso14585',
		primarySystem: 'ISO',
		description: 'Hexalobular socket pan head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '14585'
			},
			{
				system: 'DIN',
				code: '7995'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14585:2011',
		image: '/images/standards/din_7995.jpg'
	},
	{
		id: 'iso14586',
		primarySystem: 'ISO',
		description: 'Hexalobular socket countersunk head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '14586'
			},
			{
				system: 'DIN',
				code: '7995'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14586:2011'
	},
	{
		id: 'iso14587',
		primarySystem: 'ISO',
		description: 'Hexalobular socket raised countersunk (oval) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '14587'
			},
			{
				system: 'DIN',
				code: '7982'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 14587:2011'
	},
	{
		id: 'iso14588',
		primarySystem: 'ISO',
		description: 'Blind rivets — Terminology and definitions',
		designations: [
			{
				system: 'ISO',
				code: '14588'
			}
		],
		icsCode: ['21.060.40', '01.040.21'],
		reference: 'ISO 14588:2000'
	},
	{
		id: 'iso14589',
		primarySystem: 'ISO',
		description: 'Blind rivets — Mechanical testing',
		designations: [
			{
				system: 'ISO',
				code: '14589'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 14589:2000'
	},
	{
		id: 'iso15065',
		primarySystem: 'ISO',
		description:
			'Countersinks for countersunk head screws with head configuration in accordance with ISO 7721',
		designations: [
			{
				system: 'ISO',
				code: '15065'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15065:2005'
	},
	{
		id: 'iso15071',
		primarySystem: 'ISO',
		description: 'Hexagon bolts with flange — Small series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '15071'
			},
			{
				system: 'DIN',
				code: '6921'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15071:2011'
	},
	{
		id: 'iso15072',
		primarySystem: 'ISO',
		description:
			'Hexagon bolts with flange with metric fine pitch thread — Small series — Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '15072'
			},
			{
				system: 'DIN',
				code: '6921'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15072:2012'
	},
	{
		id: 'iso15480',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon washer head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15480'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15480:2019'
	},
	{
		id: 'iso15481',
		primarySystem: 'ISO',
		description: 'Cross recessed pan head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15481'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15481:1999'
	},
	{
		id: 'iso15482',
		primarySystem: 'ISO',
		description: 'Cross recessed countersunk head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15482'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15482:1999'
	},
	{
		id: 'iso15483',
		primarySystem: 'ISO',
		description: 'Cross recessed raised countersunk head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15483'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 15483:1999'
	},
	{
		id: 'iso15973',
		primarySystem: 'ISO',
		description: 'Closed end blind rivets with break pull mandrel and protruding head — AlA/St',
		designations: [
			{
				system: 'ISO',
				code: '15973'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15973:2000'
	},
	{
		id: 'iso15974',
		primarySystem: 'ISO',
		description: 'Closed end blind rivets with break pull mandrel and countersunk head — AlA/St',
		designations: [
			{
				system: 'ISO',
				code: '15974'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15974:2000'
	},
	{
		id: 'iso15975',
		primarySystem: 'ISO',
		description: 'Closed end blind rivets with break pull mandrel and protruding head — AI/AIA',
		designations: [
			{
				system: 'ISO',
				code: '15975'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15975:2002'
	},
	{
		id: 'iso15976',
		primarySystem: 'ISO',
		description: 'Closed end blind rivets with break pull mandrel and protruding head — St/St',
		designations: [
			{
				system: 'ISO',
				code: '15976'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15976:2002'
	},
	{
		id: 'iso15977',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and protruding head — AIA/St',
		designations: [
			{
				system: 'ISO',
				code: '15977'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15977:2002'
	},
	{
		id: 'iso15978',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and countersunk head — AIA/St',
		designations: [
			{
				system: 'ISO',
				code: '15978'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15978:2002'
	},
	{
		id: 'iso15979',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and protruding head — St/St',
		designations: [
			{
				system: 'ISO',
				code: '15979'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15979:2002'
	},
	{
		id: 'iso15980',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and countersunk head — St/St',
		designations: [
			{
				system: 'ISO',
				code: '15980'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15980:2002'
	},
	{
		id: 'iso15981',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and protruding head — AIA/AIA',
		designations: [
			{
				system: 'ISO',
				code: '15981'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15981:2002'
	},
	{
		id: 'iso15982',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and countersunk head — AIA/AIA',
		designations: [
			{
				system: 'ISO',
				code: '15982'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15982:2002'
	},
	{
		id: 'iso15983',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and protruding head — A2/A2',
		designations: [
			{
				system: 'ISO',
				code: '15983'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15983:2002'
	},
	{
		id: 'iso15984',
		primarySystem: 'ISO',
		description: 'Open end blind rivets with break pull mandrel and countersunk head — A2/A2',
		designations: [
			{
				system: 'ISO',
				code: '15984'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 15984:2002'
	},
	{
		id: 'iso16228',
		primarySystem: 'ISO',
		description: 'Fasteners — Types of inspection documents',
		designations: [
			{
				system: 'ISO',
				code: '16228'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 16228:2017'
	},
	{
		id: 'iso16426',
		primarySystem: 'ISO',
		description: 'Fasteners — Quality assurance system',
		designations: [
			{
				system: 'ISO',
				code: '16426'
			}
		],
		icsCode: ['21.060.01'],
		reference: 'ISO 16426:2002'
	},
	{
		id: 'iso16582',
		primarySystem: 'ISO',
		description:
			'Open end blind rivets with break pull mandrel and protruding head — Cu/St or Cu/Br or Cu/SSt',
		designations: [
			{
				system: 'ISO',
				code: '16582'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 16582:2002'
	},
	{
		id: 'iso16583',
		primarySystem: 'ISO',
		description:
			'Open end blind rivets with break pull mandrel and countersunk head — Cu/St or Cu/Br or Cu/SSt',
		designations: [
			{
				system: 'ISO',
				code: '16583'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 16583:2002'
	},
	{
		id: 'iso16584',
		primarySystem: 'ISO',
		description:
			'Open end blind rivets with break pull mandrel and protruding head — NiCu/St or NiCu/SSt',
		designations: [
			{
				system: 'ISO',
				code: '16584'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 16584:2002'
	},
	{
		id: 'iso16585',
		primarySystem: 'ISO',
		description: 'Closed end blind rivets with pull mandrel and protruding head — A2/SSt',
		designations: [
			{
				system: 'ISO',
				code: '16585'
			}
		],
		icsCode: ['21.060.40'],
		reference: 'ISO 16585:2002'
	},
	{
		id: 'iso21670',
		primarySystem: 'ISO',
		description: 'Fasteners — Hexagon weld nuts with flange',
		designations: [
			{
				system: 'ISO',
				code: '21670'
			},
			{
				system: 'DIN',
				code: '929'
			}
		],
		icsCode: ['21.060.20'],
		reference: 'ISO 21670:2014',
		image: '/images/standards/din_929.jpg'
	},
	{
		id: 'iso23429',
		primarySystem: 'ISO',
		description: 'Gauging of hexagon sockets',
		designations: [
			{
				system: 'ISO',
				code: '23429'
			},
			{
				system: 'DIN',
				code: '911'
			}
		],
		icsCode: ['21.060.10'],
		reference: 'ISO 23429:2004'
	},
	{
		id: 'din93',
		primarySystem: 'DIN',
		description: 'Tab washers with long tab',
		designations: [
			{
				system: 'DIN',
				code: '93'
			}
		],
		image: '/images/standards/din_93.jpg'
	},
	{
		id: 'din95',
		primarySystem: 'DIN',
		description: 'Slotted countersunk flat head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '95'
			}
		],
		image: '/images/standards/din_95.jpg'
	},
	{
		id: 'din96',
		primarySystem: 'DIN',
		description: 'Slotted round head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '96'
			}
		],
		image: '/images/standards/din_96.jpg'
	},
	{
		id: 'din97',
		primarySystem: 'DIN',
		description: 'Slotted countersunk flat head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '97'
			}
		],
		image: '/images/standards/din_97.jpg'
	},
	{
		id: 'din127',
		primarySystem: 'DIN',
		description: 'Spring lock washers, Type A',
		designations: [
			{
				system: 'DIN',
				code: '127'
			}
		],
		image: '/images/standards/din_127.jpg'
	},
	{
		id: 'din128',
		primarySystem: 'DIN',
		description: 'Curved spring lock washers, Type B',
		designations: [
			{
				system: 'DIN',
				code: '128'
			}
		],
		image: '/images/standards/din_128.jpg'
	},
	{
		id: 'din137',
		primarySystem: 'DIN',
		description: 'Wave spring washers, Type A',
		designations: [
			{
				system: 'DIN',
				code: '137'
			}
		],
		image: '/images/standards/din_137.jpg'
	},
	{
		id: 'din186',
		primarySystem: 'DIN',
		description: 'T-head bolts',
		designations: [
			{
				system: 'DIN',
				code: '186'
			}
		],
		image: '/images/standards/din_186.jpg'
	},
	{
		id: 'din261',
		primarySystem: 'DIN',
		description: 'T-slot bolts',
		designations: [
			{
				system: 'DIN',
				code: '261'
			}
		],
		image: '/images/standards/din_261.jpg'
	},
	{
		id: 'din315',
		primarySystem: 'DIN',
		description: 'Wing nuts, German type',
		designations: [
			{
				system: 'DIN',
				code: '315'
			}
		],
		image: '/images/standards/din_315.jpg'
	},
	{
		id: 'din316',
		primarySystem: 'DIN',
		description: 'Wing nuts, American type',
		designations: [
			{
				system: 'DIN',
				code: '316'
			}
		],
		image: '/images/standards/din_316.jpg'
	},
	{
		id: 'din404',
		primarySystem: 'DIN',
		description: 'Hexagon socket head shoulder screws',
		designations: [
			{
				system: 'DIN',
				code: '404'
			}
		],
		image: '/images/standards/din_404.jpg'
	},
	{
		id: 'din431',
		primarySystem: 'DIN',
		description: 'Pipe nuts',
		designations: [
			{
				system: 'DIN',
				code: '431'
			}
		],
		image: '/images/standards/din_431.jpg'
	},
	{
		id: 'din432',
		primarySystem: 'DIN',
		description: 'Tab washers with nose',
		designations: [
			{
				system: 'DIN',
				code: '432'
			}
		],
		image: '/images/standards/din_432.jpg'
	},
	{
		id: 'din434',
		primarySystem: 'DIN',
		description: 'Square taper washers for U-sections',
		designations: [
			{
				system: 'DIN',
				code: '434'
			}
		],
		image: '/images/standards/din_434.jpg'
	},
	{
		id: 'din435',
		primarySystem: 'DIN',
		description: 'Square taper washers for I-sections',
		designations: [
			{
				system: 'DIN',
				code: '435'
			}
		],
		image: '/images/standards/din_435.jpg'
	},
	{
		id: 'din436',
		primarySystem: 'DIN',
		description: 'Square washers for wood constructions',
		designations: [
			{
				system: 'DIN',
				code: '436'
			}
		],
		image: '/images/standards/din_436.jpg'
	},
	{
		id: 'din444',
		primarySystem: 'DIN',
		description: 'Eye bolts',
		designations: [
			{
				system: 'DIN',
				code: '444'
			}
		],
		image: '/images/standards/din_444.jpg'
	},
	{
		id: 'din462',
		primarySystem: 'DIN',
		description: 'Tab washers with 2 tabs',
		designations: [
			{
				system: 'DIN',
				code: '462'
			}
		],
		image: '/images/standards/din_462.jpg'
	},
	{
		id: 'din463',
		primarySystem: 'DIN',
		description: 'Tab washers with long tab and wing',
		designations: [
			{
				system: 'DIN',
				code: '463'
			}
		],
		image: '/images/standards/din_463.jpg'
	},
	{
		id: 'din464',
		primarySystem: 'DIN',
		description: 'Knurled thumb screws, high type',
		designations: [
			{
				system: 'DIN',
				code: '464'
			}
		],
		image: '/images/standards/din_464.jpg'
	},
	{
		id: 'din466',
		primarySystem: 'DIN',
		description: 'Knurled nuts, high type',
		designations: [
			{
				system: 'DIN',
				code: '466'
			}
		],
		image: '/images/standards/din_466.jpg'
	},
	{
		id: 'din467',
		primarySystem: 'DIN',
		description: 'Knurled nuts, low type',
		designations: [
			{
				system: 'DIN',
				code: '467'
			}
		],
		image: '/images/standards/din_467.jpg'
	},
	{
		id: 'din478',
		primarySystem: 'DIN',
		description: 'Square head bolts with collar',
		designations: [
			{
				system: 'DIN',
				code: '478'
			}
		],
		image: '/images/standards/din_478.jpg'
	},
	{
		id: 'din479',
		primarySystem: 'DIN',
		description: 'Square head bolts',
		designations: [
			{
				system: 'DIN',
				code: '479'
			}
		],
		image: '/images/standards/din_479.jpg'
	},
	{
		id: 'din480',
		primarySystem: 'DIN',
		description: 'Square head bolts with short thread',
		designations: [
			{
				system: 'DIN',
				code: '480'
			}
		],
		image: '/images/standards/din_480.jpg'
	},
	{
		id: 'din508',
		primarySystem: 'DIN',
		description: 'T-slot stones',
		designations: [
			{
				system: 'DIN',
				code: '508'
			}
		],
		image: '/images/standards/din_508.jpg'
	},
	{
		id: 'din546',
		primarySystem: 'DIN',
		description: 'Round nuts with set pin holes in side',
		designations: [
			{
				system: 'DIN',
				code: '546'
			}
		],
		image: '/images/standards/din_546.jpg'
	},
	{
		id: 'din557',
		primarySystem: 'DIN',
		description: 'Square nuts',
		designations: [
			{
				system: 'DIN',
				code: '557'
			}
		],
		image: '/images/standards/din_557.jpg'
	},
	{
		id: 'din562',
		primarySystem: 'DIN',
		description: 'Square thin nuts',
		designations: [
			{
				system: 'DIN',
				code: '562'
			}
		],
		image: '/images/standards/din_562.jpg'
	},
	{
		id: 'din564',
		primarySystem: 'DIN',
		description: 'Square head set screws with flat point',
		designations: [
			{
				system: 'DIN',
				code: '564'
			}
		],
		image: '/images/standards/din_564.jpg'
	},
	{
		id: 'din571',
		primarySystem: 'DIN',
		description: 'Hexagon head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '571'
			}
		],
		image: '/images/standards/din_571.jpg'
	},
	{
		id: 'din580',
		primarySystem: 'DIN',
		description: 'Lifting eye bolts',
		designations: [
			{
				system: 'DIN',
				code: '580'
			}
		],
		image: '/images/standards/din_580.jpg'
	},
	{
		id: 'din582',
		primarySystem: 'DIN',
		description: 'Lifting eye nuts',
		designations: [
			{
				system: 'DIN',
				code: '582'
			}
		],
		image: '/images/standards/din_582.jpg'
	},
	{
		id: 'din604',
		primarySystem: 'DIN',
		description: 'Mushroom head square neck bolts with flat bearing surface',
		designations: [
			{
				system: 'DIN',
				code: '604'
			}
		],
		image: '/images/standards/din_604.jpg'
	},
	{
		id: 'din605',
		primarySystem: 'DIN',
		description: 'Countersunk head square neck bolts',
		designations: [
			{
				system: 'DIN',
				code: '605'
			}
		],
		image: '/images/standards/din_605.jpg'
	},
	{
		id: 'din607',
		primarySystem: 'DIN',
		description: 'Cup head square neck bolts with enlarged head',
		designations: [
			{
				system: 'DIN',
				code: '607'
			}
		],
		image: '/images/standards/din_607.jpg'
	},
	{
		id: 'din608',
		primarySystem: 'DIN',
		description: 'Countersunk head square neck bolts with high square',
		designations: [
			{
				system: 'DIN',
				code: '608'
			}
		],
		image: '/images/standards/din_608.jpg'
	},
	{
		id: 'din609',
		primarySystem: 'DIN',
		description: 'Cup head square neck bolts',
		designations: [
			{
				system: 'DIN',
				code: '609'
			}
		],
		image: '/images/standards/din_609.jpg'
	},
	{
		id: 'din610',
		primarySystem: 'DIN',
		description: 'Countersunk head rivets',
		designations: [
			{
				system: 'DIN',
				code: '610'
			}
		],
		image: '/images/standards/din_610.jpg'
	},
	{
		id: 'din653',
		primarySystem: 'DIN',
		description: 'Knurled head screws',
		designations: [
			{
				system: 'DIN',
				code: '653'
			}
		],
		image: '/images/standards/din_653.jpg'
	},
	{
		id: 'din787',
		primarySystem: 'DIN',
		description: 'Hook bolts',
		designations: [
			{
				system: 'DIN',
				code: '787'
			}
		],
		image: '/images/standards/din_787.jpg'
	},
	{
		id: 'din792',
		primarySystem: 'DIN',
		description: 'Tee bolts',
		designations: [
			{
				system: 'DIN',
				code: '792'
			}
		],
		image: '/images/standards/din_792.jpg'
	},
	{
		id: 'din917',
		primarySystem: 'DIN',
		description: 'Hexagon socket pipe plugs',
		designations: [
			{
				system: 'DIN',
				code: '917'
			}
		],
		image: '/images/standards/din_917.jpg'
	},
	{
		id: 'din928',
		primarySystem: 'DIN',
		description: 'Square weld nuts',
		designations: [
			{
				system: 'DIN',
				code: '928'
			}
		],
		image: '/images/standards/din_928.jpg'
	},
	{
		id: 'din935',
		primarySystem: 'DIN',
		description: 'Hexagon castle nuts',
		designations: [
			{
				system: 'DIN',
				code: '935'
			}
		],
		image: '/images/standards/din_935.jpg'
	},
	{
		id: 'din936',
		primarySystem: 'DIN',
		description: 'Hexagon thin nuts',
		designations: [
			{
				system: 'DIN',
				code: '936'
			}
		],
		image: '/images/standards/din_936.jpg'
	},
	{
		id: 'din937',
		primarySystem: 'DIN',
		description: 'Hexagon crown nuts',
		designations: [
			{
				system: 'DIN',
				code: '937'
			}
		],
		image: '/images/standards/din_937.jpg'
	},
	{
		id: 'din979',
		primarySystem: 'DIN',
		description: 'Hexagon thin nuts with collar',
		designations: [
			{
				system: 'DIN',
				code: '979'
			}
		],
		image: '/images/standards/din_979.jpg'
	},
	{
		id: 'din981',
		primarySystem: 'DIN',
		description: 'Serrated hexagon nuts',
		designations: [
			{
				system: 'DIN',
				code: '981'
			}
		],
		image: '/images/standards/din_981.jpg'
	},
	{
		id: 'din986',
		primarySystem: 'DIN',
		description: 'Prevailing torque type hexagon domed cap nuts',
		designations: [
			{
				system: 'DIN',
				code: '986'
			}
		],
		image: '/images/standards/din_986.jpg'
	},
	{
		id: 'din988',
		primarySystem: 'DIN',
		description: 'Studs with collar',
		designations: [
			{
				system: 'DIN',
				code: '988'
			}
		],
		image: '/images/standards/din_988.jpg'
	},
	{
		id: 'din1052',
		primarySystem: 'DIN',
		description: 'Slotted round washers',
		designations: [
			{
				system: 'DIN',
				code: '1052'
			}
		],
		image: '/images/standards/din_1052.jpg'
	},
	{
		id: 'din1441',
		primarySystem: 'DIN',
		description: 'Washers for clevis pins',
		designations: [
			{
				system: 'DIN',
				code: '1441'
			}
		],
		image: '/images/standards/din_1441.jpg'
	},
	{
		id: 'din1478',
		primarySystem: 'DIN',
		description: 'Hexagon socket set screws with thrust point',
		designations: [
			{
				system: 'DIN',
				code: '1478'
			}
		],
		image: '/images/standards/din_1478.jpg'
	},
	{
		id: 'din1479',
		primarySystem: 'DIN',
		description: 'Hexagon socket head shoulder screws',
		designations: [
			{
				system: 'DIN',
				code: '1479'
			}
		],
		image: '/images/standards/din_1479.jpg'
	},
	{
		id: 'din1480',
		primarySystem: 'DIN',
		description: 'Hexagon fit bolts',
		designations: [
			{
				system: 'DIN',
				code: '1480'
			}
		],
		image: '/images/standards/din_1480.jpg'
	},
	{
		id: 'din1587',
		primarySystem: 'DIN',
		description: 'Hexagon domed cap nuts',
		designations: [
			{
				system: 'DIN',
				code: '1587'
			}
		],
		image: '/images/standards/din_1587.jpg'
	},
	{
		id: 'din1804',
		primarySystem: 'DIN',
		description: 'Fastening nuts for shaft ends',
		designations: [
			{
				system: 'DIN',
				code: '1804'
			}
		],
		image: '/images/standards/din_1804.jpg'
	},
	{
		id: 'din1816',
		primarySystem: 'DIN',
		description: 'Slotted headless screws with shank',
		designations: [
			{
				system: 'DIN',
				code: '1816'
			}
		],
		image: '/images/standards/din_1816.jpg'
	},
	{
		id: 'din2093',
		primarySystem: 'DIN',
		description: 'Disc springs',
		designations: [
			{
				system: 'DIN',
				code: '2093'
			}
		],
		image: '/images/standards/din_2093.jpg'
	},
	{
		id: 'din2510',
		primarySystem: 'DIN',
		description: 'DIN 2510 fastener',
		designations: [
			{
				system: 'DIN',
				code: '2510'
			}
		],
		image: '/images/standards/din_2510.jpg'
	},
	{
		id: 'din5406',
		primarySystem: 'DIN',
		description: 'Tapping screws for metal',
		designations: [
			{
				system: 'DIN',
				code: '5406'
			}
		],
		image: '/images/standards/din_5406.jpg'
	},
	{
		id: 'din5903',
		primarySystem: 'DIN',
		description: 'Washers for HV bolts',
		designations: [
			{
				system: 'DIN',
				code: '5903'
			}
		],
		image: '/images/standards/din_5903.jpg'
	},
	{
		id: 'din6319',
		primarySystem: 'DIN',
		description: 'Spherical washers, conical seats',
		designations: [
			{
				system: 'DIN',
				code: '6319'
			}
		],
		image: '/images/standards/din_6319.jpg'
	},
	{
		id: 'din6330',
		primarySystem: 'DIN',
		description: 'Hexagon nuts for structural steel bolting',
		designations: [
			{
				system: 'DIN',
				code: '6330'
			}
		],
		image: '/images/standards/din_6330.jpg'
	},
	{
		id: 'din6331',
		primarySystem: 'DIN',
		description: 'Spherical nuts',
		designations: [
			{
				system: 'DIN',
				code: '6331'
			}
		],
		image: '/images/standards/din_6331.jpg'
	},
	{
		id: 'din6334',
		primarySystem: 'DIN',
		description: 'Coupling nuts',
		designations: [
			{
				system: 'DIN',
				code: '6334'
			}
		],
		image: '/images/standards/din_6334.jpg'
	},
	{
		id: 'din6340',
		primarySystem: 'DIN',
		description: 'Washers for clamping devices',
		designations: [
			{
				system: 'DIN',
				code: '6340'
			}
		],
		image: '/images/standards/din_6340.jpg'
	},
	{
		id: 'din6796',
		primarySystem: 'DIN',
		description: 'Conical spring washers for bolted connections',
		designations: [
			{
				system: 'DIN',
				code: '6796'
			}
		],
		image: '/images/standards/din_6796.jpg'
	},
	{
		id: 'din6797',
		primarySystem: 'DIN',
		description: 'Countersunk serrated lock washers, Type A',
		designations: [
			{
				system: 'DIN',
				code: '6797'
			}
		],
		image: '/images/standards/din_6797.jpg'
	},
	{
		id: 'din6798',
		primarySystem: 'DIN',
		description: 'Serrated lock washers, Type J',
		designations: [
			{
				system: 'DIN',
				code: '6798'
			}
		],
		image: '/images/standards/din_6798.jpg'
	},
	{
		id: 'din6914',
		primarySystem: 'DIN',
		description: 'Hexagon socket button head screws with collar',
		designations: [
			{
				system: 'DIN',
				code: '6914'
			}
		],
		image: '/images/standards/din_6914.jpg'
	},
	{
		id: 'din6915',
		primarySystem: 'DIN',
		description: 'Hexagon socket set screws with dog point and collar',
		designations: [
			{
				system: 'DIN',
				code: '6915'
			}
		],
		image: '/images/standards/din_6915.jpg'
	},
	{
		id: 'din6916',
		primarySystem: 'DIN',
		description: 'Hexagon socket set screws with cup point and collar',
		designations: [
			{
				system: 'DIN',
				code: '6916'
			}
		],
		image: '/images/standards/din_6916.jpg'
	},
	{
		id: 'din6917',
		primarySystem: 'DIN',
		description: 'Hexagon socket countersunk head screws with collar',
		designations: [
			{
				system: 'DIN',
				code: '6917'
			}
		],
		image: '/images/standards/din_6917.jpg'
	},
	{
		id: 'din6918',
		primarySystem: 'DIN',
		description: 'Hexagon socket head cap screws with collar',
		designations: [
			{
				system: 'DIN',
				code: '6918'
			}
		],
		image: '/images/standards/din_6918.jpg'
	},
	{
		id: 'din6925',
		primarySystem: 'DIN',
		description: 'Prevailing torque type hexagon nuts with flange',
		designations: [
			{
				system: 'DIN',
				code: '6925'
			}
		],
		image: '/images/standards/din_6925.jpg'
	},
	{
		id: 'din6926',
		primarySystem: 'DIN',
		description: 'Prevailing torque type hexagon flange nuts',
		designations: [
			{
				system: 'DIN',
				code: '6926'
			}
		],
		image: '/images/standards/din_6926.jpg'
	},
	{
		id: 'din6927',
		primarySystem: 'DIN',
		description: 'Prevailing torque type all-metal hexagon flange nuts',
		designations: [
			{
				system: 'DIN',
				code: '6927'
			}
		],
		image: '/images/standards/din_6927.jpg'
	},
	{
		id: 'din7349',
		primarySystem: 'DIN',
		description: 'Shim rings',
		designations: [
			{
				system: 'DIN',
				code: '7349'
			}
		],
		image: '/images/standards/din_7349.jpg'
	},
	{
		id: 'din7603',
		primarySystem: 'DIN',
		description: 'Sealing washers',
		designations: [
			{
				system: 'DIN',
				code: '7603'
			}
		],
		image: '/images/standards/din_7603.jpg'
	},
	{
		id: 'din7965',
		primarySystem: 'DIN',
		description: 'Thread cutting screws, cross recessed pan head',
		designations: [
			{
				system: 'DIN',
				code: '7965'
			}
		],
		image: '/images/standards/din_7965.jpg'
	},
	{
		id: 'din7968',
		primarySystem: 'DIN',
		description: 'Cross recessed pan head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'DIN',
				code: '7968'
			}
		],
		image: '/images/standards/din_7968.jpg'
	},
	{
		id: 'din7969',
		primarySystem: 'DIN',
		description: 'Cross recessed countersunk head drilling screws',
		designations: [
			{
				system: 'DIN',
				code: '7969'
			}
		],
		image: '/images/standards/din_7969.jpg'
	},
	{
		id: 'din7980',
		primarySystem: 'DIN',
		description: 'Lock washers for cheese head screws',
		designations: [
			{
				system: 'DIN',
				code: '7980'
			}
		],
		image: '/images/standards/din_7980.jpg'
	},
	{
		id: 'din7984',
		primarySystem: 'DIN',
		description: 'Hexagon socket low head cap screws',
		designations: [
			{
				system: 'DIN',
				code: '7984'
			}
		],
		image: '/images/standards/din_7984.jpg'
	},
	{
		id: 'din7990',
		primarySystem: 'DIN',
		description: 'Hexagon socket set screws with flat point and brass tip',
		designations: [
			{
				system: 'DIN',
				code: '7990'
			}
		],
		image: '/images/standards/din_7990.jpg'
	},
	{
		id: 'din7991',
		primarySystem: 'DIN',
		description: 'Hexagon socket countersunk flat head screws',
		designations: [
			{
				system: 'DIN',
				code: '7991'
			}
		],
		image: '/images/standards/din_7991.jpg'
	},
	{
		id: 'din7999',
		primarySystem: 'DIN',
		description: 'Threaded studs',
		designations: [
			{
				system: 'DIN',
				code: '7999'
			}
		],
		image: '/images/standards/din_7999.jpg'
	},
	{
		id: 'din11014',
		primarySystem: 'DIN',
		description: 'Hexagon head bolts with flange',
		designations: [
			{
				system: 'DIN',
				code: '11014'
			}
		],
		image: '/images/standards/din_11014.jpg'
	},
	{
		id: 'din15237',
		primarySystem: 'DIN',
		description: 'Eye bolts for lifting purposes',
		designations: [
			{
				system: 'DIN',
				code: '15237'
			}
		],
		image: '/images/standards/din_15237.jpg'
	},
	{
		id: 'din21346',
		primarySystem: 'DIN',
		description: 'Stud bolts for flanges',
		designations: [
			{
				system: 'DIN',
				code: '21346'
			}
		],
		image: '/images/standards/din_21346.jpg'
	},
	{
		id: 'din22424',
		primarySystem: 'DIN',
		description: 'Parallel pins with internal thread',
		designations: [
			{
				system: 'DIN',
				code: '22424'
			}
		],
		image: '/images/standards/din_22424.jpg'
	},
	{
		id: 'din25193',
		primarySystem: 'DIN',
		description: 'Railway screws',
		designations: [
			{
				system: 'DIN',
				code: '25193'
			}
		],
		image: '/images/standards/din_25193.jpg'
	},
	{
		id: 'din25201',
		primarySystem: 'DIN',
		description: 'Wedge locking washers',
		designations: [
			{
				system: 'DIN',
				code: '25201'
			}
		],
		image: '/images/standards/din_25201.jpg'
	},
	{
		id: 'din34817',
		primarySystem: 'DIN',
		description: 'Spring steel disc washers',
		designations: [
			{
				system: 'DIN',
				code: '34817'
			}
		],
		image: '/images/standards/din_34817.jpg'
	},
	{
		id: 'din70852',
		primarySystem: 'DIN',
		description: 'Pan head tapping screws with collar',
		designations: [
			{
				system: 'DIN',
				code: '70852'
			}
		],
		image: '/images/standards/din_70852.jpg'
	},
	{
		id: 'din70952',
		primarySystem: 'DIN',
		description: 'Round head square neck bolts',
		designations: [
			{
				system: 'DIN',
				code: '70952'
			}
		],
		image: '/images/standards/din_70952.jpg'
	},
	{
		id: 'din74361',
		primarySystem: 'DIN',
		description: 'O-ring retaining washers',
		designations: [
			{
				system: 'DIN',
				code: '74361'
			}
		],
		image: '/images/standards/din_74361.jpg'
	},
	{
		id: 'din80701',
		primarySystem: 'DIN',
		description: 'Wing screws',
		designations: [
			{
				system: 'DIN',
				code: '80701'
			}
		],
		image: '/images/standards/din_80701.jpg'
	},
	{
		id: 'din80705',
		primarySystem: 'DIN',
		description: 'Wing screws with rounded wings',
		designations: [
			{
				system: 'DIN',
				code: '80705'
			}
		],
		image: '/images/standards/din_80705.jpg'
	}
] as const;
