/**
 * GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated by scripts/standards-build.js
 * To update, modify the source data and run: pnpm standards:build
 *
 * Generated: 2026-01-11T15:52:23.212Z
 * Total standards: 210
 * ISO standards: 104
 * DIN standards: 106
 * Standards with images: 155
 */

import type { ISODINStandard, HardwareType } from './standards';

/**
 * Generated list of fastener standards with cross-references
 */
export const generatedStandards: ISODINStandard[] = [
	{
		id: 'iso10509',
		primarySystem: 'ISO',
		description: 'ISO 10509',
		designations: [
			{
				system: 'ISO',
				code: '10509'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso14584',
		primarySystem: 'ISO',
		description: 'ISO 14584',
		designations: [
			{
				system: 'ISO',
				code: '14584'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din93',
		primarySystem: 'DIN',
		description: 'Tab Washers with long tab',
		designations: [
			{
				system: 'DIN',
				code: '93'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_93.png'
	},
	{
		id: 'din95',
		primarySystem: 'DIN',
		description: 'Slotted raised countersunk (oval) head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '95'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_95.png'
	},
	{
		id: 'din96',
		primarySystem: 'DIN',
		description: 'Slotted round head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '96'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_96.png'
	},
	{
		id: 'din97',
		primarySystem: 'DIN',
		description: 'Slotted countersunk (flat) head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '97'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_97.png'
	},
	{
		id: 'din127',
		primarySystem: 'DIN',
		description: 'Spring Lock Washers',
		designations: [
			{
				system: 'DIN',
				code: '127'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_127.png'
	},
	{
		id: 'din128',
		primarySystem: 'DIN',
		description: 'Curved spring lock washers',
		designations: [
			{
				system: 'DIN',
				code: '128'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_128.png'
	},
	{
		id: 'din137',
		primarySystem: 'DIN',
		description:
			'Cold-forming taps for ISO metric coarse pitch thread M2 to M39 and ISO metric fine pitch thread M3 × 0,25 to M52 × 4 - Dimensions',
		designations: [
			{
				system: 'DIN',
				code: '137'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din186',
		primarySystem: 'DIN',
		description: 'T-head bolts with square neck',
		designations: [
			{
				system: 'DIN',
				code: '186'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_186.png'
	},
	{
		id: 'din261',
		primarySystem: 'DIN',
		description: 'T-head bolts',
		designations: [
			{
				system: 'DIN',
				code: '261'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_261.png'
	},
	{
		id: 'din315',
		primarySystem: 'DIN',
		description: 'Fasteners - Wing nuts - Rounded wings',
		designations: [
			{
				system: 'DIN',
				code: '315'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_315.png'
	},
	{
		id: 'din316',
		primarySystem: 'DIN',
		description: 'Fasteners - Wing screws - Rounded wings',
		designations: [
			{
				system: 'DIN',
				code: '316'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_316.png'
	},
	{
		id: 'din404',
		primarySystem: 'DIN',
		description: 'Slotted capstan screws',
		designations: [
			{
				system: 'DIN',
				code: '404'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_404.png'
	},
	{
		id: 'din431',
		primarySystem: 'DIN',
		description: 'Pipe nuts with thread according to DIN EN ISO 228-1',
		designations: [
			{
				system: 'DIN',
				code: '431'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_431.png'
	},
	{
		id: 'din432',
		primarySystem: 'DIN',
		description: 'Locking tab washers',
		designations: [
			{
				system: 'DIN',
				code: '432'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_432.png'
	},
	{
		id: 'din434',
		primarySystem: 'DIN',
		description: 'Square taper washers for U-sections',
		designations: [
			{
				system: 'DIN',
				code: '434'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_434.png'
	},
	{
		id: 'din435',
		primarySystem: 'DIN',
		description: 'Square taper washers for I-sections',
		designations: [
			{
				system: 'DIN',
				code: '435'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_435.png'
	},
	{
		id: 'din436',
		primarySystem: 'DIN',
		description: 'Square washers, especially for wood constructions',
		designations: [
			{
				system: 'DIN',
				code: '436'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_436.png'
	},
	{
		id: 'din444',
		primarySystem: 'DIN',
		description: 'Fasteners - Eye bolts',
		designations: [
			{
				system: 'DIN',
				code: '444'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_444.png'
	},
	{
		id: 'din462',
		primarySystem: 'DIN',
		description:
			'Machine tools - Internal tab washers for slotted round nuts in conformity with DIN 1804',
		designations: [
			{
				system: 'DIN',
				code: '462'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_462.png'
	},
	{
		id: 'din463',
		primarySystem: 'DIN',
		description: 'Washers with 2 taps',
		designations: [
			{
				system: 'DIN',
				code: '463'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_463.png'
	},
	{
		id: 'din464',
		primarySystem: 'DIN',
		description: 'Knurled thumb screws, high type',
		designations: [
			{
				system: 'DIN',
				code: '464'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_464.png'
	},
	{
		id: 'din466',
		primarySystem: 'DIN',
		description: 'Knurled nuts - High type',
		designations: [
			{
				system: 'DIN',
				code: '466'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_466.png'
	},
	{
		id: 'din467',
		primarySystem: 'DIN',
		description: 'Knurled nuts - Low type',
		designations: [
			{
				system: 'DIN',
				code: '467'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_467.png'
	},
	{
		id: 'din471',
		primarySystem: 'DIN',
		description: 'Retaining rings for shafts - Normal type and heavy type',
		designations: [
			{
				system: 'DIN',
				code: '471'
			}
		],
		hardwareType: 'ring' as HardwareType,
		image: '/images/standards/din_471.png'
	},
	{
		id: 'din472',
		primarySystem: 'DIN',
		description: 'Retaining rings for bores - Normal type and heavy type',
		designations: [
			{
				system: 'DIN',
				code: '472'
			}
		],
		hardwareType: 'ring' as HardwareType,
		image: '/images/standards/din_472.png'
	},
	{
		id: 'din478',
		primarySystem: 'DIN',
		description: 'Square head bolts with collar',
		designations: [
			{
				system: 'DIN',
				code: '478'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_478.png'
	},
	{
		id: 'din479',
		primarySystem: 'DIN',
		description: 'DIN 479',
		designations: [
			{
				system: 'DIN',
				code: '479'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din480',
		primarySystem: 'DIN',
		description: 'DIN 480',
		designations: [
			{
				system: 'DIN',
				code: '480'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din508',
		primarySystem: 'DIN',
		description: 'Nuts for T-slots',
		designations: [
			{
				system: 'DIN',
				code: '508'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_508.png'
	},
	{
		id: 'din546',
		primarySystem: 'DIN',
		description: 'Slotted round nuts',
		designations: [
			{
				system: 'DIN',
				code: '546'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_546.png'
	},
	{
		id: 'din557',
		primarySystem: 'DIN',
		description: 'Fasteners - Square nuts - Product grade C',
		designations: [
			{
				system: 'DIN',
				code: '557'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_557.png'
	},
	{
		id: 'din562',
		primarySystem: 'DIN',
		description: 'Square thin nuts - Product grade B',
		designations: [
			{
				system: 'DIN',
				code: '562'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_557.png'
	},
	{
		id: 'din564',
		primarySystem: 'DIN',
		description: 'DIN 564',
		designations: [
			{
				system: 'DIN',
				code: '564'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din571',
		primarySystem: 'DIN',
		description: 'Hexagon head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '571'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_571.png'
	},
	{
		id: 'din580',
		primarySystem: 'DIN',
		description: 'DIN 580',
		designations: [
			{
				system: 'DIN',
				code: '580'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din582',
		primarySystem: 'DIN',
		description: 'DIN 582',
		designations: [
			{
				system: 'DIN',
				code: '582'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din604',
		primarySystem: 'DIN',
		description: 'Flat countersunk head nib bolts',
		designations: [
			{
				system: 'DIN',
				code: '604'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_604.png'
	},
	{
		id: 'din605',
		primarySystem: 'DIN',
		description: 'Flat countersunk head square neck bolts with long square',
		designations: [
			{
				system: 'DIN',
				code: '605'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_605.png'
	},
	{
		id: 'din607',
		primarySystem: 'DIN',
		description: 'Cup head nib bolts',
		designations: [
			{
				system: 'DIN',
				code: '607'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_607.png'
	},
	{
		id: 'din608',
		primarySystem: 'DIN',
		description: 'DIN 608',
		designations: [
			{
				system: 'DIN',
				code: '608'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'din609',
		primarySystem: 'DIN',
		description: 'Hexagon fits bolts with long thread',
		designations: [
			{
				system: 'DIN',
				code: '609'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_609.png'
	},
	{
		id: 'din610',
		primarySystem: 'DIN',
		description: 'Hexagon fit bolts with short reduced threaded portion; metric thread',
		designations: [
			{
				system: 'DIN',
				code: '610'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_610.png'
	},
	{
		id: 'din653',
		primarySystem: 'DIN',
		description: 'Knurled thumb screws, low type',
		designations: [
			{
				system: 'DIN',
				code: '653'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_653.png'
	},
	{
		id: 'din787',
		primarySystem: 'DIN',
		description: 'Bolts and screws for T-slots',
		designations: [
			{
				system: 'DIN',
				code: '787'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_787.png'
	},
	{
		id: 'din792',
		primarySystem: 'DIN',
		description: 'DIN 792',
		designations: [
			{
				system: 'DIN',
				code: '792'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din917',
		primarySystem: 'DIN',
		description: 'Hexagon cap nuts, low type',
		designations: [
			{
				system: 'DIN',
				code: '917'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_917.png'
	},
	{
		id: 'din928',
		primarySystem: 'DIN',
		description: 'Square weld nuts',
		designations: [
			{
				system: 'DIN',
				code: '928'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_928.png'
	},
	{
		id: 'din935',
		primarySystem: 'DIN',
		description: 'Castle nuts - metric thread, finish m, mg and g',
		designations: [
			{
				system: 'DIN',
				code: '935'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_935.png'
	},
	{
		id: 'din936',
		primarySystem: 'DIN',
		description: 'Hexagon lock nuts, metric thread',
		designations: [
			{
				system: 'DIN',
				code: '936'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_439.png'
	},
	{
		id: 'din937',
		primarySystem: 'DIN',
		description: 'Low castle nuts; metric thread',
		designations: [
			{
				system: 'DIN',
				code: '937'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_937.png'
	},
	{
		id: 'din979',
		primarySystem: 'DIN',
		description:
			'Hexagon thin slotted and castle nuts - Metric coarse and fine pitch thread, product grades A and B',
		designations: [
			{
				system: 'DIN',
				code: '979'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_979.png'
	},
	{
		id: 'din981',
		primarySystem: 'DIN',
		description: 'Rolling bearings - Locknuts',
		designations: [
			{
				system: 'DIN',
				code: '981'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_981.png'
	},
	{
		id: 'din986',
		primarySystem: 'DIN',
		description: 'Prevailing torque type hexagon domed cap nuts with nonmetallic insert',
		designations: [
			{
				system: 'DIN',
				code: '986'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_986.png'
	},
	{
		id: 'din988',
		primarySystem: 'DIN',
		description: 'Shim rings and supporting rings',
		designations: [
			{
				system: 'DIN',
				code: '988'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_988.png'
	},
	{
		id: 'iso1051',
		primarySystem: 'DIN',
		description: 'ISO 1051',
		designations: [
			{
				system: 'ISO',
				code: '1051'
			},
			{
				system: 'DIN',
				code: '660'
			}
		],
		hardwareType: 'rivet' as HardwareType
	},
	{
		id: 'din1052',
		primarySystem: 'DIN',
		description: 'DIN 1052',
		designations: [
			{
				system: 'DIN',
				code: '1052'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso1207',
		primarySystem: 'DIN',
		description: 'Slotted cheese head screws - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '1207'
			},
			{
				system: 'DIN',
				code: '84'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_84.png'
	},
	{
		id: 'iso1234',
		primarySystem: 'DIN',
		description: 'ISO 1234',
		designations: [
			{
				system: 'ISO',
				code: '1234'
			},
			{
				system: 'DIN',
				code: '94'
			}
		],
		hardwareType: 'pin' as HardwareType
	},
	{
		id: 'din1441',
		primarySystem: 'DIN',
		description: 'DIN 1441',
		designations: [
			{
				system: 'DIN',
				code: '1441'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din1478',
		primarySystem: 'DIN',
		description: 'DIN 1478',
		designations: [
			{
				system: 'DIN',
				code: '1478'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso1479',
		primarySystem: 'DIN',
		description: 'Hexagon head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '1479'
			},
			{
				system: 'DIN',
				code: '7976'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7976.png'
	},
	{
		id: 'din1479',
		primarySystem: 'DIN',
		description: 'Hexagon turnbuckles',
		designations: [
			{
				system: 'DIN',
				code: '1479'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_1479.png'
	},
	{
		id: 'din1480',
		primarySystem: 'DIN',
		description: 'DIN 1480',
		designations: [
			{
				system: 'DIN',
				code: '1480'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso1481',
		primarySystem: 'DIN',
		description: 'ISO 1481',
		designations: [
			{
				system: 'ISO',
				code: '1481'
			},
			{
				system: 'DIN',
				code: '7971'
			}
		],
		hardwareType: 'self_tapping' as HardwareType
	},
	{
		id: 'iso1482',
		primarySystem: 'DIN',
		description: 'ISO 1482',
		designations: [
			{
				system: 'ISO',
				code: '1482'
			},
			{
				system: 'DIN',
				code: '7972'
			}
		],
		hardwareType: 'self_tapping' as HardwareType
	},
	{
		id: 'iso1483',
		primarySystem: 'DIN',
		description: 'ISO 1483',
		designations: [
			{
				system: 'ISO',
				code: '1483'
			},
			{
				system: 'DIN',
				code: '7973'
			}
		],
		hardwareType: 'self_tapping' as HardwareType
	},
	{
		id: 'iso1580',
		primarySystem: 'DIN',
		description: 'Slotted pan head screws - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '1580'
			},
			{
				system: 'DIN',
				code: '85'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_85.png'
	},
	{
		id: 'din1587',
		primarySystem: 'DIN',
		description: 'Hexagon cap nuts, high type',
		designations: [
			{
				system: 'DIN',
				code: '1587'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_1587.png'
	},
	{
		id: 'din1804',
		primarySystem: 'DIN',
		description: 'Slotted Round Nut for Hook Spanner; ISO Metric Fine Thread',
		designations: [
			{
				system: 'DIN',
				code: '1804'
			}
		],
		hardwareType: 'nut' as HardwareType
	},
	{
		id: 'din1816',
		primarySystem: 'DIN',
		description: 'Round Nut with Set Pin Holes Inside; ISO Metric Fine Thread',
		designations: [
			{
				system: 'DIN',
				code: '1816'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_1816.png'
	},
	{
		id: 'iso2009',
		primarySystem: 'DIN',
		description: 'Slotted countersunk flat head screws - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '2009'
			},
			{
				system: 'DIN',
				code: '963'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_963.png'
	},
	{
		id: 'iso2010',
		primarySystem: 'DIN',
		description: 'Slotted raised countersunk head screws - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '2010'
			},
			{
				system: 'DIN',
				code: '964'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_964.png'
	},
	{
		id: 'din2093',
		primarySystem: 'DIN',
		description: 'Disc springs; dimensions and quality specifications',
		designations: [
			{
				system: 'DIN',
				code: '2093'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_2093.png'
	},
	{
		id: 'iso2338',
		primarySystem: 'DIN',
		description: 'Parallel pins, of unhardened steel and austenitic stainless steel',
		designations: [
			{
				system: 'ISO',
				code: '2338'
			},
			{
				system: 'DIN',
				code: '7'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7.png'
	},
	{
		id: 'iso2339',
		primarySystem: 'DIN',
		description: 'Taper pins, unhardened',
		designations: [
			{
				system: 'ISO',
				code: '2339'
			},
			{
				system: 'DIN',
				code: '1'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1.png'
	},
	{
		id: 'iso2340',
		primarySystem: 'DIN',
		description: 'ISO 2340',
		designations: [
			{
				system: 'ISO',
				code: '2340'
			},
			{
				system: 'DIN',
				code: '1433'
			}
		],
		hardwareType: 'pin' as HardwareType
	},
	{
		id: 'iso2341',
		primarySystem: 'DIN',
		description: 'Clevis pins with head',
		designations: [
			{
				system: 'ISO',
				code: '2341'
			},
			{
				system: 'DIN',
				code: '1443'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1444.png'
	},
	{
		id: 'iso2342',
		primarySystem: 'DIN',
		description: 'ISO 2342',
		designations: [
			{
				system: 'ISO',
				code: '2342'
			},
			{
				system: 'DIN',
				code: '551'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din2510',
		primarySystem: 'DIN',
		description: 'Bolted Connections with Reduced Shank - Extension Sleeves',
		designations: [
			{
				system: 'DIN',
				code: '2510'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_2510.png'
	},
	{
		id: 'iso3506',
		primarySystem: 'DIN',
		description: 'ISO 3506',
		designations: [
			{
				system: 'ISO',
				code: '3506'
			},
			{
				system: 'DIN',
				code: '267'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso4014',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon head bolts - Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '4014'
			},
			{
				system: 'DIN',
				code: '931'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/iso_4014.png'
	},
	{
		id: 'iso4016',
		primarySystem: 'DIN',
		description: 'ISO 4016',
		designations: [
			{
				system: 'ISO',
				code: '4016'
			},
			{
				system: 'DIN',
				code: '601'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso4017',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon head screws - Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '4017'
			},
			{
				system: 'DIN',
				code: '933'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/iso_4014.png'
	},
	{
		id: 'iso4018',
		primarySystem: 'DIN',
		description: 'ISO 4018',
		designations: [
			{
				system: 'ISO',
				code: '4018'
			},
			{
				system: 'DIN',
				code: '558'
			},
			{
				system: 'DIN',
				code: '561'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso4026',
		primarySystem: 'DIN',
		description: 'ISO 4026',
		designations: [
			{
				system: 'ISO',
				code: '4026'
			},
			{
				system: 'DIN',
				code: '913'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso4027',
		primarySystem: 'DIN',
		description: 'ISO 4027',
		designations: [
			{
				system: 'ISO',
				code: '4027'
			},
			{
				system: 'DIN',
				code: '914'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso4028',
		primarySystem: 'DIN',
		description: 'ISO 4028',
		designations: [
			{
				system: 'ISO',
				code: '4028'
			},
			{
				system: 'DIN',
				code: '915'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso4029',
		primarySystem: 'DIN',
		description: 'ISO 4029',
		designations: [
			{
				system: 'ISO',
				code: '4029'
			},
			{
				system: 'DIN',
				code: '916'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso4032',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon regular nuts (style 1)',
		designations: [
			{
				system: 'ISO',
				code: '4032'
			},
			{
				system: 'DIN',
				code: '934'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/iso_4032.png'
	},
	{
		id: 'iso4033',
		primarySystem: 'DIN',
		description: 'ISO 4033',
		designations: [
			{
				system: 'ISO',
				code: '4033'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_982.png'
	},
	{
		id: 'iso4035',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon thin nuts (style 0)',
		designations: [
			{
				system: 'ISO',
				code: '4035'
			},
			{
				system: 'DIN',
				code: '439'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_439.png'
	},
	{
		id: 'iso4162',
		primarySystem: 'DIN',
		description: 'ISO 4162',
		designations: [
			{
				system: 'ISO',
				code: '4162'
			},
			{
				system: 'DIN',
				code: '6921'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_6921.png'
	},
	{
		id: 'iso4762',
		primarySystem: 'DIN',
		description: 'Hexagon socket head cap screws',
		designations: [
			{
				system: 'ISO',
				code: '4762'
			},
			{
				system: 'DIN',
				code: '912'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_912.png'
	},
	{
		id: 'iso4766',
		primarySystem: 'DIN',
		description: 'ISO 4766',
		designations: [
			{
				system: 'ISO',
				code: '4766'
			},
			{
				system: 'DIN',
				code: '1481'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_1481.png'
	},
	{
		id: 'din5406',
		primarySystem: 'DIN',
		description: 'DIN 5406',
		designations: [
			{
				system: 'DIN',
				code: '5406'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din5903',
		primarySystem: 'DIN',
		description: 'DIN 5903',
		designations: [
			{
				system: 'DIN',
				code: '5903'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din6319',
		primarySystem: 'DIN',
		description: 'Spherical Washers; Conical Seats; Clamp bolt heads; countersink',
		designations: [
			{
				system: 'DIN',
				code: '6319'
			}
		],
		hardwareType: 'washer' as HardwareType
	},
	{
		id: 'din6330',
		primarySystem: 'DIN',
		description: 'Hexagon nuts with a height of 1,5 d',
		designations: [
			{
				system: 'DIN',
				code: '6330'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6330.png'
	},
	{
		id: 'din6331',
		primarySystem: 'DIN',
		description: 'Hexagon collar nuts with a height of 1,5 d',
		designations: [
			{
				system: 'DIN',
				code: '6331'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6331.png'
	},
	{
		id: 'din6334',
		primarySystem: 'DIN',
		description: 'Hexagon slotted nuts - Part 3: Metric coarse pitch thread, product grade C',
		designations: [
			{
				system: 'DIN',
				code: '6334'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6334.png'
	},
	{
		id: 'din6340',
		primarySystem: 'DIN',
		description: 'Washers for clamping devices',
		designations: [
			{
				system: 'DIN',
				code: '6340'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_6340.png'
	},
	{
		id: 'din6796',
		primarySystem: 'DIN',
		description: 'Conical spring washers for bolted connections',
		designations: [
			{
				system: 'DIN',
				code: '6796'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_6796.png'
	},
	{
		id: 'din6797',
		primarySystem: 'DIN',
		description: 'Toothed lock washers',
		designations: [
			{
				system: 'DIN',
				code: '6797'
			}
		],
		hardwareType: 'washer' as HardwareType
	},
	{
		id: 'din6798',
		primarySystem: 'DIN',
		description: 'Serrated lock washers',
		designations: [
			{
				system: 'DIN',
				code: '6798'
			}
		],
		hardwareType: 'washer' as HardwareType
	},
	{
		id: 'din6914',
		primarySystem: 'DIN',
		description:
			'Hexagon bolts with large widths across flats for steel structures (joints with high-tensile, prestressed bolts)',
		designations: [
			{
				system: 'DIN',
				code: '6914'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_6914.png'
	},
	{
		id: 'din6915',
		primarySystem: 'DIN',
		description:
			'Sechskantmuttern mit großen Schlüsselweiten, für HV-Verbindungen in Stahlkonstruktionen',
		designations: [
			{
				system: 'DIN',
				code: '6915'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_6915.png'
	},
	{
		id: 'din6916',
		primarySystem: 'DIN',
		description: 'Washers for steel structures (joint with high-tensile, prestressed bolts)',
		designations: [
			{
				system: 'DIN',
				code: '6916'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_6916.png'
	},
	{
		id: 'din6917',
		primarySystem: 'DIN',
		description: 'DIN 6917',
		designations: [
			{
				system: 'DIN',
				code: '6917'
			}
		],
		hardwareType: 'washer' as HardwareType
	},
	{
		id: 'din6918',
		primarySystem: 'DIN',
		description: 'DIN 6918',
		designations: [
			{
				system: 'DIN',
				code: '6918'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din6923',
		primarySystem: 'DIN',
		description: 'Hexagon nuts with flange',
		designations: [
			{
				system: 'DIN',
				code: '6923'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6923.png'
	},
	{
		id: 'din6925',
		primarySystem: 'DIN',
		description: 'Prevailing torque type all-metall hexagon nuts',
		designations: [
			{
				system: 'DIN',
				code: '6925'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6925.png'
	},
	{
		id: 'din6926',
		primarySystem: 'DIN',
		description: 'Prevailing torque type hexagon nuts with flange and with non-metallic insert',
		designations: [
			{
				system: 'DIN',
				code: '6926'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6926.png'
	},
	{
		id: 'din6927',
		primarySystem: 'DIN',
		description: 'Prevailing torque type all-metal nuts with flange',
		designations: [
			{
				system: 'DIN',
				code: '6927'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6927.png'
	},
	{
		id: 'iso7040',
		primarySystem: 'DIN',
		description:
			'Fasteners - Prevailing torque hexagon nuts - Regular nuts (with non-metallic insert)',
		designations: [
			{
				system: 'ISO',
				code: '7040'
			},
			{
				system: 'DIN',
				code: '985'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_982.png'
	},
	{
		id: 'iso7041',
		primarySystem: 'DIN',
		description: 'ISO 7041',
		designations: [
			{
				system: 'ISO',
				code: '7041'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_982.png'
	},
	{
		id: 'iso7042',
		primarySystem: 'DIN',
		description: 'Fasteners - Prevailing torque hexagon nuts - High nuts (all metal)',
		designations: [
			{
				system: 'ISO',
				code: '7042'
			},
			{
				system: 'DIN',
				code: '980'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_6925.png'
	},
	{
		id: 'iso7045',
		primarySystem: 'DIN',
		description: 'Pan head screws with type H or type Z cross recess - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7045'
			},
			{
				system: 'DIN',
				code: '7985'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7985.png'
	},
	{
		id: 'iso7046',
		primarySystem: 'DIN',
		description:
			'Countersunk flat head screws (common head style) with type H or type Z cross recess - Product grade A - Part 1: Steel screws of property class 4.8 (ISO 7046-1:2011); German version EN ISO 7046-1:2011',
		designations: [
			{
				system: 'ISO',
				code: '7046'
			},
			{
				system: 'DIN',
				code: '965'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_965.png'
	},
	{
		id: 'iso7047',
		primarySystem: 'DIN',
		description:
			'Raised countersunk head screws (common head style) with type H or type Z cross recess - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7047'
			},
			{
				system: 'DIN',
				code: '966'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_966.png'
	},
	{
		id: 'iso7048',
		primarySystem: 'DIN',
		description: 'ISO 7048',
		designations: [
			{
				system: 'ISO',
				code: '7048'
			},
			{
				system: 'DIN',
				code: '7971'
			}
		],
		hardwareType: 'self_tapping' as HardwareType
	},
	{
		id: 'iso7049',
		primarySystem: 'DIN',
		description: 'Cross-recessed pan head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7049'
			},
			{
				system: 'DIN',
				code: '7981'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7981.png'
	},
	{
		id: 'iso7050',
		primarySystem: 'DIN',
		description: 'Cross-recessed countersunk (flat) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7050'
			},
			{
				system: 'DIN',
				code: '7982'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7982.png'
	},
	{
		id: 'iso7051',
		primarySystem: 'DIN',
		description: 'Cross-recessed raised countersunk (oval) head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7051'
			},
			{
				system: 'DIN',
				code: '7983'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7983.png'
	},
	{
		id: 'iso7053',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon washer head tapping screws',
		designations: [
			{
				system: 'ISO',
				code: '7053'
			},
			{
				system: 'DIN',
				code: '7967'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/iso_7053.png'
	},
	{
		id: 'iso7089',
		primarySystem: 'DIN',
		description: 'Plain washers - Normal series - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7089'
			},
			{
				system: 'DIN',
				code: '125'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_125.png'
	},
	{
		id: 'iso7090',
		primarySystem: 'DIN',
		description: 'ISO 7090',
		designations: [
			{
				system: 'ISO',
				code: '7090'
			},
			{
				system: 'DIN',
				code: '125'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_125.png'
	},
	{
		id: 'iso7091',
		primarySystem: 'DIN',
		description: 'Plain washers - Normal series - Product grade C',
		designations: [
			{
				system: 'ISO',
				code: '7091'
			},
			{
				system: 'DIN',
				code: '126'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_126.png'
	},
	{
		id: 'iso7092',
		primarySystem: 'DIN',
		description: 'Plain washers - Small series - Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '7092'
			},
			{
				system: 'DIN',
				code: '433'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_433.png'
	},
	{
		id: 'iso7093',
		primarySystem: 'DIN',
		description:
			'Plain washers - Large series - Part 2: Product grade C (ISO 7093-2:2000); German version EN ISO 7093-2:2000',
		designations: [
			{
				system: 'ISO',
				code: '7093'
			},
			{
				system: 'DIN',
				code: '9021'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_9021.png'
	},
	{
		id: 'iso7094',
		primarySystem: 'DIN',
		description: 'Plain washers - Extra large series - Product grade C',
		designations: [
			{
				system: 'ISO',
				code: '7094'
			},
			{
				system: 'DIN',
				code: '440'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_440.png'
	},
	{
		id: 'din7349',
		primarySystem: 'DIN',
		description: 'Plain washers for bolts with heavy clamping sleeves',
		designations: [
			{
				system: 'DIN',
				code: '7349'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_7349.png'
	},
	{
		id: 'iso7379',
		primarySystem: 'DIN',
		description: 'Hexagon socket head shoulder screws',
		designations: [
			{
				system: 'ISO',
				code: '7379'
			},
			{
				system: 'DIN',
				code: '6912'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/iso_7379.png'
	},
	{
		id: 'iso7380',
		primarySystem: 'DIN',
		description:
			'Fasteners - Button head screws with reduced loadability - Part 1: Hexagon socket button head screws (ISO 7380-1:2022); German version EN ISO 7380-1:2023',
		designations: [
			{
				system: 'ISO',
				code: '7380'
			},
			{
				system: 'DIN',
				code: '9427'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/iso_7380.png'
	},
	{
		id: 'iso7434',
		primarySystem: 'DIN',
		description: 'ISO 7434',
		designations: [
			{
				system: 'ISO',
				code: '7434'
			},
			{
				system: 'DIN',
				code: '553'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso7435',
		primarySystem: 'DIN',
		description: 'ISO 7435',
		designations: [
			{
				system: 'ISO',
				code: '7435'
			},
			{
				system: 'DIN',
				code: '417'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso7436',
		primarySystem: 'DIN',
		description: 'ISO 7436',
		designations: [
			{
				system: 'ISO',
				code: '7436'
			},
			{
				system: 'DIN',
				code: '438'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din7603',
		primarySystem: 'DIN',
		description: 'Sealing rings',
		designations: [
			{
				system: 'DIN',
				code: '7603'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_7603.png'
	},
	{
		id: 'iso7719',
		primarySystem: 'DIN',
		description: 'ISO 7719',
		designations: [
			{
				system: 'ISO',
				code: '7719'
			},
			{
				system: 'DIN',
				code: '980'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_980.png'
	},
	{
		id: 'iso7720',
		primarySystem: 'DIN',
		description: 'ISO 7720',
		designations: [
			{
				system: 'ISO',
				code: '7720'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_982.png'
	},
	{
		id: 'din7965',
		primarySystem: 'DIN',
		description: 'Screwed inserts (Screw plugs)',
		designations: [
			{
				system: 'DIN',
				code: '7965'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7965.png'
	},
	{
		id: 'din7968',
		primarySystem: 'DIN',
		description: 'Hexagon fit bolts with hexagon nut for steel structures',
		designations: [
			{
				system: 'DIN',
				code: '7968'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7968.png'
	},
	{
		id: 'din7969',
		primarySystem: 'DIN',
		description: 'Slotted countersunk head bolts with hexagon nut for steel structures',
		designations: [
			{
				system: 'DIN',
				code: '7969'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7969.png'
	},
	{
		id: 'din7980',
		primarySystem: 'DIN',
		description: 'Spring lock washers with spuare ends for cheese head screws',
		designations: [
			{
				system: 'DIN',
				code: '7980'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_7980.png'
	},
	{
		id: 'din7984',
		primarySystem: 'DIN',
		description: 'Hexagon socket head cap screws with low head with reduced loadability',
		designations: [
			{
				system: 'DIN',
				code: '7984'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7984.png'
	},
	{
		id: 'din7990',
		primarySystem: 'DIN',
		description: 'Hexagon head bolts with hexagon nut for steel structures',
		designations: [
			{
				system: 'DIN',
				code: '7990'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7990.png'
	},
	{
		id: 'din7991',
		primarySystem: 'DIN',
		description: 'Hexagon socket countersunk head screws',
		designations: [
			{
				system: 'DIN',
				code: '7991'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7991.png'
	},
	{
		id: 'din7997',
		primarySystem: 'DIN',
		description: 'Cross recessed countersunk head wood screws',
		designations: [
			{
				system: 'DIN',
				code: '7997'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7997.png'
	},
	{
		id: 'din7999',
		primarySystem: 'DIN',
		description:
			'High strength hexagon fit bolts with large widths across flats for structural steel bolting',
		designations: [
			{
				system: 'DIN',
				code: '7999'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7999.png'
	},
	{
		id: 'iso8673',
		primarySystem: 'DIN',
		description: 'ISO 8673',
		designations: [
			{
				system: 'ISO',
				code: '8673'
			},
			{
				system: 'DIN',
				code: '934'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_934.png'
	},
	{
		id: 'iso8674',
		primarySystem: 'DIN',
		description: 'ISO 8674',
		designations: [
			{
				system: 'ISO',
				code: '8674'
			},
			{
				system: 'DIN',
				code: '982'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_982.png'
	},
	{
		id: 'iso8675',
		primarySystem: 'DIN',
		description: 'ISO 8675',
		designations: [
			{
				system: 'ISO',
				code: '8675'
			},
			{
				system: 'DIN',
				code: '439'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_439.png'
	},
	{
		id: 'iso8676',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon head screws, with fine pitch thread - Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '8676'
			},
			{
				system: 'DIN',
				code: '961'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_961.png'
	},
	{
		id: 'iso8678',
		primarySystem: 'DIN',
		description: 'ISO 8678',
		designations: [
			{
				system: 'ISO',
				code: '8678'
			},
			{
				system: 'DIN',
				code: '603'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_603.png'
	},
	{
		id: 'iso8733',
		primarySystem: 'DIN',
		description: 'ISO 8733',
		designations: [
			{
				system: 'ISO',
				code: '8733'
			},
			{
				system: 'DIN',
				code: '7979'
			}
		],
		hardwareType: 'pin' as HardwareType
	},
	{
		id: 'iso8734',
		primarySystem: 'DIN',
		description: 'Parallel pins, of hardened steel and martensitic stainless steel (Dowel pins)',
		designations: [
			{
				system: 'ISO',
				code: '8734'
			},
			{
				system: 'DIN',
				code: '6325'
			},
			{
				system: 'DIN',
				code: '7'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_6325.png'
	},
	{
		id: 'iso8735',
		primarySystem: 'DIN',
		description:
			'Parallel pins with internal thread, of hardened steel and martensitic stainless steel',
		designations: [
			{
				system: 'ISO',
				code: '8735'
			},
			{
				system: 'DIN',
				code: '7978'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7979d.png'
	},
	{
		id: 'iso8736',
		primarySystem: 'DIN',
		description: 'Taper pins with internal thread, unhardened',
		designations: [
			{
				system: 'ISO',
				code: '8736'
			},
			{
				system: 'DIN',
				code: '7977'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7978.png'
	},
	{
		id: 'iso8737',
		primarySystem: 'DIN',
		description: 'Taper pins with external thread, unhardened',
		designations: [
			{
				system: 'ISO',
				code: '8737'
			},
			{
				system: 'DIN',
				code: '7977'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_258.png'
	},
	{
		id: 'iso8738',
		primarySystem: 'DIN',
		description: 'Plain washers for clevis pins; Product grade A',
		designations: [
			{
				system: 'ISO',
				code: '8738'
			},
			{
				system: 'DIN',
				code: '1440'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_1440.png'
	},
	{
		id: 'iso8740',
		primarySystem: 'DIN',
		description:
			'Fasteners - Parallel grooved pins, with chamfer point - Full-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '8740'
			},
			{
				system: 'DIN',
				code: '1473'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1473.png'
	},
	{
		id: 'iso8741',
		primarySystem: 'DIN',
		description: 'Fasteners - Reverse-taper grooved pins - Half-length progressive grooves',
		designations: [
			{
				system: 'ISO',
				code: '8741'
			},
			{
				system: 'DIN',
				code: '1474'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1474.png'
	},
	{
		id: 'iso8744',
		primarySystem: 'DIN',
		description: 'Fasteners - Taper grooved pins - Full-length progressive grooves',
		designations: [
			{
				system: 'ISO',
				code: '8744'
			},
			{
				system: 'DIN',
				code: '1471'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1471.png'
	},
	{
		id: 'iso8745',
		primarySystem: 'DIN',
		description: 'Fasteners - Taper grooved pins - Half-length progressive grooves',
		designations: [
			{
				system: 'ISO',
				code: '8745'
			},
			{
				system: 'DIN',
				code: '1472'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1472.png'
	},
	{
		id: 'iso8746',
		primarySystem: 'DIN',
		description: 'Fasteners - Grooved pins with round head - Full-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '8746'
			},
			{
				system: 'DIN',
				code: '1476'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1476.png'
	},
	{
		id: 'iso8747',
		primarySystem: 'DIN',
		description: 'Fasteners - Grooved pins with countersunk head - Full-length diamond grooves',
		designations: [
			{
				system: 'ISO',
				code: '8747'
			},
			{
				system: 'DIN',
				code: '1477'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1477.png'
	},
	{
		id: 'iso8748',
		primarySystem: 'DIN',
		description: 'Spring-type straight pins - Coiled, heavy duty',
		designations: [
			{
				system: 'ISO',
				code: '8748'
			},
			{
				system: 'DIN',
				code: '7343'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7344.png'
	},
	{
		id: 'iso8750',
		primarySystem: 'DIN',
		description: 'Spring-type straight pins - Coiled, standard duty',
		designations: [
			{
				system: 'ISO',
				code: '8750'
			},
			{
				system: 'DIN',
				code: '7343'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7343.png'
	},
	{
		id: 'iso8751',
		primarySystem: 'DIN',
		description: 'ISO 8751',
		designations: [
			{
				system: 'ISO',
				code: '8751'
			},
			{
				system: 'DIN',
				code: '7343'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7343.png'
	},
	{
		id: 'iso8752',
		primarySystem: 'DIN',
		description: 'Spring-type straight pins - Slotted, heavy duty',
		designations: [
			{
				system: 'ISO',
				code: '8752'
			},
			{
				system: 'DIN',
				code: '1481'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_1481.png'
	},
	{
		id: 'iso8765',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon head bolts, with fine pitch thread - Product grades A and B',
		designations: [
			{
				system: 'ISO',
				code: '8765'
			},
			{
				system: 'DIN',
				code: '960'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_960.png'
	},
	{
		id: 'iso10510',
		primarySystem: 'DIN',
		description: 'ISO 10510',
		designations: [
			{
				system: 'ISO',
				code: '10510'
			},
			{
				system: 'DIN',
				code: '6902'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso10511',
		primarySystem: 'DIN',
		description:
			'Fasteners - Prevailing torque hexagon nuts - Thin nuts (with non-metallic insert)',
		designations: [
			{
				system: 'ISO',
				code: '10511'
			},
			{
				system: 'DIN',
				code: '985'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_985.png'
	},
	{
		id: 'iso10512',
		primarySystem: 'DIN',
		description: 'ISO 10512',
		designations: [
			{
				system: 'ISO',
				code: '10512'
			},
			{
				system: 'DIN',
				code: '985'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_985.png'
	},
	{
		id: 'iso10513',
		primarySystem: 'DIN',
		description: 'ISO 10513',
		designations: [
			{
				system: 'ISO',
				code: '10513'
			},
			{
				system: 'DIN',
				code: '980'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_980.png'
	},
	{
		id: 'iso10642',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon socket countersunk head screws with reduced loadability',
		designations: [
			{
				system: 'ISO',
				code: '10642'
			},
			{
				system: 'DIN',
				code: '7991'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7991.png'
	},
	{
		id: 'iso10644',
		primarySystem: 'DIN',
		description: 'ISO 10644',
		designations: [
			{
				system: 'ISO',
				code: '10644'
			},
			{
				system: 'DIN',
				code: '7981'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_7981.png'
	},
	{
		id: 'iso10669',
		primarySystem: 'DIN',
		description: 'ISO 10669',
		designations: [
			{
				system: 'ISO',
				code: '10669'
			},
			{
				system: 'DIN',
				code: '6902'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso10673',
		primarySystem: 'DIN',
		description: 'ISO 10673',
		designations: [
			{
				system: 'ISO',
				code: '10673'
			},
			{
				system: 'DIN',
				code: '6902'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din11014',
		primarySystem: 'DIN',
		description: 'DIN 11014',
		designations: [
			{
				system: 'DIN',
				code: '11014'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso12474',
		primarySystem: 'DIN',
		description: 'ISO 12474',
		designations: [
			{
				system: 'ISO',
				code: '12474'
			},
			{
				system: 'DIN',
				code: '912'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_912.png'
	},
	{
		id: 'iso13337',
		primarySystem: 'DIN',
		description: 'Spring-type straight pins - Slotted, light duty',
		designations: [
			{
				system: 'ISO',
				code: '13337'
			},
			{
				system: 'DIN',
				code: '7346'
			}
		],
		hardwareType: 'pin' as HardwareType,
		image: '/images/standards/din_7346.png'
	},
	{
		id: 'iso14579',
		primarySystem: 'DIN',
		description: 'ISO 14579',
		designations: [
			{
				system: 'ISO',
				code: '14579'
			},
			{
				system: 'DIN',
				code: '34822'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso14580',
		primarySystem: 'DIN',
		description: 'Hexalobular socket cheese head screws',
		designations: [
			{
				system: 'ISO',
				code: '14580'
			},
			{
				system: 'DIN',
				code: '34823'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7984.png'
	},
	{
		id: 'iso14581',
		primarySystem: 'DIN',
		description: 'ISO 14581',
		designations: [
			{
				system: 'ISO',
				code: '14581'
			},
			{
				system: 'DIN',
				code: '7988'
			}
		],
		hardwareType: 'screw' as HardwareType
	},
	{
		id: 'iso14582',
		primarySystem: 'DIN',
		description: 'ISO 14582',
		designations: [
			{
				system: 'ISO',
				code: '14582'
			},
			{
				system: 'DIN',
				code: '7989'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso14583',
		primarySystem: 'DIN',
		description: 'Hexalobular socket pan head screws',
		designations: [
			{
				system: 'ISO',
				code: '14583'
			},
			{
				system: 'DIN',
				code: '7996'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_7985.png'
	},
	{
		id: 'iso14585',
		primarySystem: 'DIN',
		description: 'ISO 14585',
		designations: [
			{
				system: 'ISO',
				code: '14585'
			},
			{
				system: 'DIN',
				code: '7995'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso14586',
		primarySystem: 'DIN',
		description: 'ISO 14586',
		designations: [
			{
				system: 'ISO',
				code: '14586'
			},
			{
				system: 'DIN',
				code: '7995'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso14587',
		primarySystem: 'DIN',
		description: 'ISO 14587',
		designations: [
			{
				system: 'ISO',
				code: '14587'
			},
			{
				system: 'DIN',
				code: '7982'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7982.png'
	},
	{
		id: 'iso15071',
		primarySystem: 'DIN',
		description: 'ISO 15071',
		designations: [
			{
				system: 'ISO',
				code: '15071'
			},
			{
				system: 'DIN',
				code: '6921'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_6921.png'
	},
	{
		id: 'iso15072',
		primarySystem: 'DIN',
		description: 'ISO 15072',
		designations: [
			{
				system: 'ISO',
				code: '15072'
			},
			{
				system: 'DIN',
				code: '6921'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_6921.png'
	},
	{
		id: 'din15237',
		primarySystem: 'DIN',
		description:
			'Continuous mechanical handling equipment; seating screws and cupped washers for the attachment of components to belts',
		designations: [
			{
				system: 'DIN',
				code: '15237'
			}
		],
		hardwareType: 'washer' as HardwareType,
		image: '/images/standards/din_15237.png'
	},
	{
		id: 'iso15480',
		primarySystem: 'DIN',
		description: 'Fasteners - Hexagon washer head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15480'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/iso_15480.png'
	},
	{
		id: 'iso15481',
		primarySystem: 'DIN',
		description: 'Cross recessed pan head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15481'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7504m.png'
	},
	{
		id: 'iso15482',
		primarySystem: 'DIN',
		description: 'Cross recessed countersunk head drilling screws with tapping screw thread',
		designations: [
			{
				system: 'ISO',
				code: '15482'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		hardwareType: 'self_tapping' as HardwareType,
		image: '/images/standards/din_7504o.png'
	},
	{
		id: 'iso15483',
		primarySystem: 'DIN',
		description: 'ISO 15483',
		designations: [
			{
				system: 'ISO',
				code: '15483'
			},
			{
				system: 'DIN',
				code: '7504'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_7504.png'
	},
	{
		id: 'din21346',
		primarySystem: 'DIN',
		description: 'DIN 21346',
		designations: [
			{
				system: 'DIN',
				code: '21346'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'iso21670',
		primarySystem: 'DIN',
		description: 'ISO 21670',
		designations: [
			{
				system: 'ISO',
				code: '21670'
			},
			{
				system: 'DIN',
				code: '929'
			}
		],
		hardwareType: 'other' as HardwareType,
		image: '/images/standards/din_929.png'
	},
	{
		id: 'din22424',
		primarySystem: 'DIN',
		description: 'Firedamp-proof and explosion-proof instruments; three-square bolts',
		designations: [
			{
				system: 'DIN',
				code: '22424'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_22424.png'
	},
	{
		id: 'iso23429',
		primarySystem: 'DIN',
		description: 'ISO 23429',
		designations: [
			{
				system: 'ISO',
				code: '23429'
			},
			{
				system: 'DIN',
				code: '911'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din25193',
		primarySystem: 'DIN',
		description: 'DIN 25193',
		designations: [
			{
				system: 'DIN',
				code: '25193'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din25201',
		primarySystem: 'DIN',
		description: 'Railway vehicles; retention of bolted assemblies; in general',
		designations: [
			{
				system: 'DIN',
				code: '25201'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_25201.png'
	},
	{
		id: 'din34817',
		primarySystem: 'DIN',
		description: 'DIN 34817',
		designations: [
			{
				system: 'DIN',
				code: '34817'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din70852',
		primarySystem: 'DIN',
		description: 'Groove nuts; dimensions',
		designations: [
			{
				system: 'DIN',
				code: '70852'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_70852.png'
	},
	{
		id: 'din70952',
		primarySystem: 'DIN',
		description: 'DIN 70952',
		designations: [
			{
				system: 'DIN',
				code: '70952'
			}
		],
		hardwareType: 'other' as HardwareType
	},
	{
		id: 'din74361',
		primarySystem: 'DIN',
		description:
			'Disc wheels for motor vehicles and trailers - Part 1: Connection dimensions for bolt- and mixed centering',
		designations: [
			{
				system: 'DIN',
				code: '74361'
			}
		],
		hardwareType: 'screw' as HardwareType,
		image: '/images/standards/din_74361.png'
	},
	{
		id: 'din80701',
		primarySystem: 'DIN',
		description: 'Wing nuts',
		designations: [
			{
				system: 'DIN',
				code: '80701'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_80701.png'
	},
	{
		id: 'din80705',
		primarySystem: 'DIN',
		description:
			'Thin nuts with small widths across flats - Coarse pitch thread, fine pitch thread',
		designations: [
			{
				system: 'DIN',
				code: '80705'
			}
		],
		hardwareType: 'nut' as HardwareType,
		image: '/images/standards/din_80705.png'
	}
] as const;
